### ISSUE TITLE
当出现滚动条的时候，框选范围和edge线条的位置错乱

### ISSUE THREAD

**Issue by shaojun427** [alibaba/butterfly#116]
现在的定位都是根据client的原点来的 而不是画布起始位置

**Comment by shaojun427** [comment]
![test](https://user-images.githubusercontent.com/16127112/57686928-0d68de00-766d-11e9-95f2-83b31d2321b9.gif)

**Comment by noonnightstorm** [comment]
2.8.x及以上已经解决
