### ISSUE TITLE
如何启动项目

### ISSUE THREAD

**Issue by AaronChenchen** [alibaba/butterfly#186]
作者您好，我将项目pull 下来之后，安装完依赖，请问如何启动项目呢？如有建议，请告知我，谢谢！

**Comment by cctv1005s** [comment]
就知道有这个问题

 @noonnightstorm 快出来挨打

**Comment by noonnightstorm** [comment]
@AaronChenchen 这两天我上传下源码。您可以在https://noonnightstorm.github.io/#/introduction?_k=9fo48a 这里在线编辑哈～

**Comment by AaronChenchen** [comment]
好的，谢谢！@noonnightstorm
