### ISSUE TITLE
节点，线，节点组上下顺序需要整理

### ISSUE THREAD

**Issue by noonnightstorm** [alibaba/butterfly#210]
节点组外：
1: 节点要在线上面
2: 节点要在节点组下面

节点组内
1: 节点在节点组上面
2: 节点组内的线要在节点组上面
3: 节点组外的线要在节点组下面

**Comment by AceLeeWinnie** [comment]
建议取消 .butterfly-dag {pointer-events: auto;}
禁止了用户自定义连线 hover
