### ISSUE TITLE
[需求]希望可以优化动态改变Edge组件的label

### ISSUE THREAD

**Issue by woaiaogege** [alibaba/butterfly#218]
1.动态改变label样式和显示
2.增加api可以快速更改
![image](https://user-images.githubusercontent.com/28804096/75663041-22ba0200-5cab-11ea-98c4-3fd6bd205311.png)

**Comment by noonnightstorm** [comment]
这个可以自己拓展：只需要将edge里面添加updateLabel的方法，你自己可以按照自己的需求修改this.labelDom里面的dom
