### ISSUE TITLE
【需求】期望新增画布适配和批量动画聚焦功能

### ISSUE THREAD

**Issue by AceLeeWinnie** [alibaba/butterfly#23]
1. 画布适配，画布所有节点和边缩放至全都在可视区域的状态
2. 批量动画聚焦，目前 focusNodeWithAnimate 仅支持单个节点的聚焦，没办法聚焦节点相关部分（如聚焦以这个节点为中心的其他节点）

**Comment by noonnightstorm** [comment]
在2.0.12版本里面focusNodesWithAnimate和focusCenterWithAnimate能帮到你

**Comment by AceLeeWinnie** [comment]
Efficient! Thanks so much!
