### ISSUE TITLE
节点和连线拖动到画布边缘时，画布自动延展

### ISSUE THREAD

**Issue by AceLeeWinnie** [alibaba/butterfly#242]
**您想申请的是需求还是问题？**
需求
**目前的情况是什么？**
无
**预期的结果是什么？**
自动延展画布
**哪个butterfly版本在哪个浏览器／操作系统发生的错误？**

**请重现步骤，如果可以的话，请提供一个最小的演示案例。**

**Comment by noonnightstorm** [comment]
已解决
