### ISSUE TITLE
拖拽连线没有undo

### ISSUE THREAD

**Issue by lth707** [alibaba/butterfly#270]
**您想申请的是需求还是问题？**
拖拽连线没有undo
**目前的情况是什么？**
拖拽连线没有undo
**预期的结果是什么？**
拖拽连线要有undo
**哪个butterfly版本在哪个浏览器／操作系统发生的错误？**

**请重现步骤，如果可以的话，请提供一个最小的演示案例。**

**Comment by noonnightstorm** [comment]
已解决
