### ISSUE TITLE
动态增加节点

### ISSUE THREAD

**Issue by withlin** [alibaba/butterfly#283]
**您想申请的是需求还是问题？**
问题
**目前的情况是什么？**
当只有一个root节点在画板上，如何动态的新增画板？
**预期的结果是什么？**
动态新增node
**哪个butterfly版本在哪个浏览器／操作系统发生的错误？**
google浏览器。windows10. butterfly master版本
**请重现步骤，如果可以的话，请提供一个最小的演示案例。**

**Comment by noonnightstorm** [comment]
你可以根据你的需要来实例化Canvas对象，new Canvas即可。

**Comment by laik** [comment]
> 你可以根据你的需要来实例化Canvas对象，new Canvas即可。

目前的情况是什么？
当只有一个root节点在画板上，如何动态的新增在画板上新增node
预期的结果是什么？
动态新增node

**Comment by laik** [comment]
@noonnightstorm
