### ISSUE TITLE
需求--在线可视化编辑

### ISSUE THREAD

**Issue by bo11zhou** [alibaba/butterfly#286]
我提1个需求：
使用Butterfly，从无到有，可视化地维护1个图定义。

这个有实现的计划嘛？

**Comment by noonnightstorm** [comment]
小蝴蝶最近的计划是：从代码编写 -> 节点画布的沉淀，大家可以基础沉淀来二次开发 -> 可视化的搭建节点和画布。咱们一步一步来哈～

**Comment by bo11zhou** [comment]
> 小蝴蝶最近的计划是：从代码编写 -> 节点画布的沉淀，大家可以基础沉淀来二次开发 -> 可视化的搭建节点和画布。咱们一步一步来哈～

关注

**Comment by noonnightstorm** [comment]
节点画布的沉淀大概在6月中正式发布给大伙们使用，敬请关注
