### ISSUE TITLE
如何跟vue一起使用呢？

### ISSUE THREAD

**Issue by bigfacewo** [alibaba/butterfly#288]
**您想申请的是需求还是问题？**
需求
**目前的情况是什么？**
我发现使用数据驱动这一点很符合vue的模式，但是如果要自定义node的话，我该如何改造成使用vue的组件呢？尤其是使用vue的单文件组件。这一点还不是太明白，希望能得到一些指点，非常感谢！
**预期的结果是什么？**
能够配合vue一起使用

**Comment by noonnightstorm** [comment]
现在暂时只支持和react配合使用，暂时还不能和vue配合使用，抱歉

**Comment by bigfacewo** [comment]
@noonnightstorm 好的 谢谢回复

**Comment by LaveyD** [comment]
```
// index.vue
<template>
  <div id="dag-canvas"></div>
</template>

<script>
import FlowChartCanvas from './canvas';
import { mockData } from './data';

const Node = require('./node.js');

export default {
  name: 'FlowChart',
  mounted() {
    const root = document.getElementById('dag-canvas');
    this.canvas = new FlowChartCanvas({
       root,
       ...
     });
    this.canvas.draw(mockData, {}, () => {
      this.canvas.focusCenterWithAnimate();
    });
    this.canvas.on('events', (data) => {
      console.log(data);
    });
  },
}
</script>

<style lang="less">
@import '~butterfly-dag/pack/index.css';
@import './node.less';
</style>
```

```
// canvas.js
import { Canvas } from 'butterfly-dag/pack/index';

class FlowChartCanvas extends Canvas {
  constructor(...args) {
    super(...args);
    this.listenEventProxy();
  }
  listenEventProxy() {}
  ...
}

export default FlowChartCanvas;
```

node.js 和example里的基本一样

**Comment by noonnightstorm** [comment]
> ```
> // index.vue
> <template>
>   <div id="dag-canvas"></div>
> </template>
> 
> <script>
> import FlowChartCanvas from './canvas';
> import { mockData } from './data';
> 
> const Node = require('./node.js');
> 
> export default {
>   name: 'FlowChart',
>   mounted() {
>     const root = document.getElementById('dag-canvas');
>     this.canvas = new FlowChartCanvas({
>        root,
>        ...
>      });
>     this.canvas.draw(mockData, {}, () => {
>       this.canvas.focusCenterWithAnimate();
>     });
>     this.canvas.on('events', (data) => {
>       console.log(data);
>     });
>   },
> }
> </script>
> 
> <style lang="less">
> @import '~butterfly-dag/pack/index.css';
> @import './node.less';
> </style>
> ```
> 
> ```
> // canvas.js
> import { Canvas } from 'butterfly-dag/pack/index';
> 
> class FlowChartCanvas extends Canvas {
>   constructor(...args) {
>     super(...args);
>     this.listenEventProxy();
>   }
>   listenEventProxy() {}
>   ...
> }
> 
> export default FlowChartCanvas;
> ```
> 
> node.js 和example里的基本一样

我这两天会写一个react最佳实践，请问到时候方便贡献一下文档，提供个vue最佳实践呢？

**Comment by LaveyD** [comment]
> > ```
> > // index.vue
> > <template>
> >   <div id="dag-canvas"></div>
> > </template>
> > 
> > <script>
> > import FlowChartCanvas from './canvas';
> > import { mockData } from './data';
> > 
> > const Node = require('./node.js');
> > 
> > export default {
> >   name: 'FlowChart',
> >   mounted() {
> >     const root = document.getElementById('dag-canvas');
> >     this.canvas = new FlowChartCanvas({
> >        root,
> >        ...
> >      });
> >     this.canvas.draw(mockData, {}, () => {
> >       this.canvas.focusCenterWithAnimate();
> >     });
> >     this.canvas.on('events', (data) => {
> >       console.log(data);
> >     });
> >   },
> > }
> > </script>
> > 
> > <style lang="less">
> > @import '~butterfly-dag/pack/index.css';
> > @import './node.less';
> > </style>
> > ```
> > 
> > 
> > ```
> > // canvas.js
> > import { Canvas } from 'butterfly-dag/pack/index';
> > 
> > class FlowChartCanvas extends Canvas {
> >   constructor(...args) {
> >     super(...args);
> >     this.listenEventProxy();
> >   }
> >   listenEventProxy() {}
> >   ...
> > }
> > 
> > export default FlowChartCanvas;
> > ```
> > 
> > 
> > node.js 和example里的基本一样
> 
> 我这两天会写一个react最佳实践，请问到时候方便贡献一下文档，提供个vue最佳实践呢？

好的，这个组件挺好用的，赞
