### ISSUE TITLE
能通过引用.js文件的方式使用吗

### ISSUE THREAD

**Issue by AngelDaShiXiong** [alibaba/butterfly#290]
**您想申请的是需求还是问题？**
问题
主要做后端，React实在没整明白，想请教一下能否通过<script>标签引入.js文件依赖的方式使用butterfly？

**Comment by noonnightstorm** [comment]
可以，可以通过script引入。咱们可以配合着react使用

**Comment by noonnightstorm** [comment]
不过建议你使用的话还是使用umi等脚手架，会给你带来很多便利

**Comment by AngelDaShiXiong** [comment]
> 不过建议你使用的话还是使用umi等脚手架，会给你带来很多便利

好的谢谢您

**Comment by AngelDaShiXiong** [comment]
> 可以，可以通过script引入。咱们可以配合着react使用

大佬，请问能给一个helloworld那样的简单的demo吗，，，现在这个demo实在太复杂了，另外在线编辑调试的站点https://noonnightstorm.github.io/访问就报403。。。

**Comment by noonnightstorm** [comment]
在线的demo准备上线中
