### ISSUE TITLE
请问有对应这张预览图里面的demo源码吗？

### ISSUE THREAD

**Issue by acpplife** [alibaba/butterfly#305]
![demo](https://gt-toolbox.oss-cn-beijing.aliyuncs.com/gt-toolbox/67f69070-a6d1-43bf-8172-bc2880589fc5.png)
请问有首页提供的预览图里面这张图片对应的demo吗？感谢~~~

**Comment by noonnightstorm** [comment]
这张图是咱们内部的业务，暂时不能提供demo源码，抱歉哈～

**Comment by acpplife** [comment]
哦哦，谢谢回复~
