### ISSUE TITLE
升级到2.8.25报错

### ISSUE THREAD

**Issue by acpplife** [alibaba/butterfly#324]
升级到2.8.25版本之后报错：
```
This relative module was not found:

* ./circleLayout in ./node_modules/_butterfly-dag@2.8.25@butterfly-dag/pack/index.js
```

**Comment by noonnightstorm** [comment]
抱歉，已经升级2.8.26了

**Comment by acpplife** [comment]
大佬，好像升级到2.8.26还是这样呢~
```
"butterfly-dag": "^2.8.26"
```
```
* ./circleLayout in ./node_modules/_butterfly-dag@2.8.26@butterfly-dag/pack/index.js
```

**Comment by noonnightstorm** [comment]
> 大佬，好像升级到2.8.26还是这样呢~
> 
> ```
> "butterfly-dag": "^2.8.26"
> ```
> 
> ```
> * ./circleLayout in ./node_modules/_butterfly-dag@2.8.26@butterfly-dag/pack/index.js
> ```

稍等，我看看

**Comment by noonnightstorm** [comment]
> 大佬，好像升级到2.8.26还是这样呢~
> 
> ```
> "butterfly-dag": "^2.8.26"
> ```
> 
> ```
> * ./circleLayout in ./node_modules/_butterfly-dag@2.8.26@butterfly-dag/pack/index.js
> ```

抱歉，已修复，请使用：butterfly-dag@2.8.29
