### ISSUE TITLE
点击某个节点时，与其相关的节点和线颜色高亮显示，目前支持么。

### ISSUE THREAD

**Issue by githubcai1** [alibaba/butterfly#331]
**您想申请的是需求还是问题？**

**目前的情况是什么？**

**预期的结果是什么？**

**哪个butterfly版本在哪个浏览器／操作系统发生的错误？**

**请重现步骤，如果可以的话，请提供一个最小的演示案例。**

**Comment by noonnightstorm** [comment]
支持，canvas下有getNeighborEdges的方法或者相邻的边，当然边信息里面也会有相邻的节点

**Comment by githubcai1** [comment]
> 支持，canvas下有getNeighborEdges的方法或者相邻的边，当然边信息里面也会有相邻的节点

哇，回复超级快，让我有了方向，之前都想非常感谢，第一次接触此类需求，canvas之前不怎么了解,我去再看下，目前是需要用原生的canvas去重新渲染么，后续会考虑封装此功能么，再次感谢。

**Comment by noonnightstorm** [comment]
哈哈，刚好看到，你看看canvas的api即可

**Comment by githubcai1** [comment]
&nbsp;&nbsp;
&nbsp; 大佬您好，
&nbsp; &nbsp; &nbsp; &nbsp;冒昧的打扰下，我又来找你啦。git上我没有URL去挂载图片，就写邮件找您了。希望抽个帮忙看下，
&nbsp; &nbsp; &nbsp; &nbsp;需求是 寻找一条线上的相关节点，点击某一个节点，高亮显示相关的节点及线。
&nbsp; &nbsp; &nbsp; &nbsp;已下图最右侧 文档3-A 为例，点击时 文档1-A,文档1-B,文档2-A 高亮， 文档2-B不高亮。
&nbsp; &nbsp; &nbsp; &nbsp;就是推导下一个 相关节点与初始方向有关，不往回再查找。 文档3-A --》文档2-A --》 文档1-A,文档1-B ，但是 文档1-B 不去回找 文档2-A和文档2-B；如果是中间节点则往两边推导相关节点。
&nbsp; &nbsp; &nbsp; &nbsp;希望大佬能再回复一次，目前API中&nbsp;getNeighborNodesAndEdgesByLevel 好像是查找所有相关的节点和线。万分感谢。
&nbsp; &nbsp; &nbsp;&nbsp;

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/butterfly"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月21日(星期二) 下午4:31
收件人:&nbsp;"alibaba/butterfly"<butterfly@noreply.github.com&gt;;
抄送:&nbsp;"epms"<379583039@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/butterfly] 点击某个节点时，与其相关的节点和线颜色高亮显示，目前支持么。 (#331)





 
哈哈，刚好看到，你看看canvas的api即可
