### ISSUE TITLE
获取相邻节点，然后获取的节点不往回查找相邻节点

### ISSUE THREAD

**Issue by githubcai1** [alibaba/butterfly#332]
需求是 寻找一条线上的相关节点，点击某一个节点，高亮显示相关的节点及线。
       已下图最右侧 文档3-A 为例，点击时 文档1-A,文档1-B,文档2-A 高亮， 文档2-B不高亮。
       就是推导下一个 相关节点与初始方向有关，不往回再查找。 文档3-A --》文档2-A --》 文档1-A,文档1-B ，但是 文档1-B 不去回找 文档2-A和文档2-B；如果是中间节点则往两边推导相关节点。
       希望大佬能再回复一次，目前API中 getNeighborNodesAndEdgesByLevel 好像是查找所有相关的节点和线。万分感谢。
![demo](https://user-images.githubusercontent.com/25893230/88650940-c6dd9300-d0fb-11ea-8aa8-387bd9f2a611.png)

**Comment by noonnightstorm** [comment]
这个好像@Jiang Haichao 解决过

**Comment by noonnightstorm** [comment]
这个好像@AceLeeWinnie解决过

**Comment by githubcai1** [comment]
> 这个好像@AceLeeWinnie解决过

谢谢，我先去了解下。我看了源码中查找相邻节点的实现方式，有了初步方向，我先试着自己去实现下。再次谢谢回复。

**Comment by githubcai1** [comment]
@AceLeeWinnie  大佬有方案么。

**Comment by AceLeeWinnie** [comment]
> @AceLeeWinnie 大佬有方案么。

一个方法是构建正逆两个邻接表进行 DFS。不管点击哪个节点，按出入两个方向查找。

getNeighborNodesAndEdgesByLevel 方法支持按方向查找的，三参 type = 'in' 按入向查找，type = 'out' 按出向查找，type = 'all' 双向查找。

**Comment by githubcai1** [comment]
> > @AceLeeWinnie大佬有方案么。
> 
> 一个方法是合成正逆两个双向表进行DFS。无论单击哪个变量，按出入两个方向查找。
> 
> getNeighborNodesAndEdgesByLevel方法支持按方向查找的，三参type ='in'按入向查找，type ='out'按出向查找，type ='all'双向查找。

感谢感谢，看到大神指点，豁然开朗，之前没搞明白type的三种值代表的含义，刚才试了下，的确如您所说的一样。
