### ISSUE TITLE
在微信小程序和app的webview中访问H5页面时，节点之间的连线位置不正确

### ISSUE THREAD

**Issue by tanlixiong** [alibaba/butterfly#336]
**您想申请的是需求还是问题？**

**目前的情况是什么？**

**预期的结果是什么？**

**哪个butterfly版本在哪个浏览器／操作系统发生的错误？**

**请重现步骤，如果可以的话，请提供一个最小的演示案例。**

**Comment by tanlixiong** [comment]
![image](https://user-images.githubusercontent.com/5153774/90207535-17056680-de19-11ea-9223-46abdbb56a0b.png)
![image](https://user-images.githubusercontent.com/5153774/90207585-3a301600-de19-11ea-88e8-77aa94340da0.png)

**Comment by tanlixiong** [comment]
使用环境是：windows 、微信小程序和APP的webview、在vue环境下引用，同一个H5页面在PC端没有问题，只在小程序和APP中有问题。
版本是2.8.29，是这几天通过指令npm install butterfly-dag进行安装的

**Comment by noonnightstorm** [comment]
好的，收到，之前一直没兼容app和小程序，这几天咱们尽快调整兼容好

**Comment by noonnightstorm** [comment]
> 使用环境是：windows 、微信小程序和APP的webview、在vue环境下引用，同一个H5页面在PC端没有问题，只在小程序和APP中有问题。
> 版本是2.8.29，是这几天通过指令npm install butterfly-dag进行安装的

butterfly-dag@2.8.30已经可以适配手机的分辨率，但部分事件还没兼容到，你遇到可以随时给我反馈
