### ISSUE TITLE
Demo里有不少大小写拼写错误

### ISSUE THREAD

**Issue by oyzhen** [alibaba/butterfly#338]
ERROR in ./demo/circle/index.jsx
Module not found: Error: Can't resolve './CircleCanvas.js' in '/home/om/studies/butterfly/example/demo/circle'
 @ ./demo/circle/index.jsx 35:13-41
 @ ./index.jsx

ERROR in ./index.jsx
Module not found: Error: Can't resolve './demo/DrageLayout/index.jsx' in '/home/om/studies/butterfly/example'
 @ ./index.jsx 103:15-54

ERROR in ../src/utils/layout/hierarchy/index.js
Module not found: Error: Can't resolve '@antv/hierarchy' in '/home/om/studies/butterfly/src/utils/layout/hierarchy'
 @ ../src/utils/layout/hierarchy/index.js 7:16-42
 @ ../src/canvas/treeCanvas.js
 @ ../index.js
 @ ./demo/emergency/index.jsx
 @ ./index.jsx

ERROR in ../src/utils/layout/layout.js
Module not found: Error: Can't resolve 'dagre' in '/home/om/studies/butterfly/src/utils/layout'
 @ ../src/utils/layout/layout.js 17:12-28
 @ ../index.js
 @ ./demo/emergency/index.jsx
 @ ./index.jsx

**Comment by noonnightstorm** [comment]
我们立马去修改，一直使用mac，对大小写无感

**Comment by noonnightstorm** [comment]
已修复
