### ISSUE TITLE
 节点-树状布局的收缩和展开，API文档打不开，目前功能支持么

### ISSUE THREAD

**Issue by githubcai1** [alibaba/butterfly#350]
**您想申请的是需求还是问题？**
   问题
**目前的情况是什么？**
 节点-树状布局的收缩和展开，API文档打不开，目前功能支持么
**预期的结果是什么？**
  
**哪个butterfly版本在哪个浏览器／操作系统发生的错误？**

**请重现步骤，如果可以的话，请提供一个最小的演示案例。**

**Comment by noonnightstorm** [comment]
支持的。我已经补齐文档了。很抱歉之前加了这个feat忘记写文档了。
