### ISSUE TITLE
butterfly未来的计划是什么，是否会长期维护下去

### ISSUE THREAD

**Issue by wehuss** [alibaba/butterfly#352]
目前阿里有GGEditor,X6,butterfly，但都存在文档不全的情况。
本人已经在项目中使用了GGEditor,但苦于其更新慢文档少导致易用性过低打算弃用。
在v2ex看到了butterfly的推广文章，觉得这是我想要的，不知道这恶鬼项目是否会长期维护下去

**Comment by noonnightstorm** [comment]
butetrfly当然会一直维护下去，我也可以给你分享下咱们的计划：
1: 正在补齐所有布局（目前正在支持grid，fruchterman，国庆前发布）
2: 正在支持react和vue的最佳实践（预估国庆后出）
3: 会添加右键菜单，tips的插件
4: 画布低代码搭建平台，后续基本不需要写代码就能搭建dag了（这个已经80%了，准备发布）
5: 智能化dag，后续直接从手稿识别成小蝴蝶组件（长远目标）

**Comment by noonnightstorm** [comment]
你有问题随时留issue，除了节假日，基本都能当天回

**Comment by wehuss** [comment]
@noonnightstorm 感谢回复，加油！
