### ISSUE TITLE
连线拖动创建,删除及事件响应问题

### ISSUE THREAD

**Issue by caopanwei** [alibaba/butterfly#353]
**您想申请的是需求还是问题？**

需求和问题都有

**目前的情况是什么？**

参考了#345中用到的vue的demo

1.点击连线中间位置无法响应link:click事件, 其他位置偶尔不行
![image](https://user-images.githubusercontent.com/6239286/93211700-2d923b00-f794-11ea-9eaa-42837be6fdf7.png)

2.点击node节点偏上的位置进行拖动位置, 鼠标移动速度较快时,鼠标总是被移出node区域, node不再移动也没有释放拖动事件
![image](https://user-images.githubusercontent.com/6239286/93212013-9aa5d080-f794-11ea-94b5-c70e2207cec8.png)

3. 拖动进行连线,刚开始显示线条这个样式 ,到第二个节点才显示正常

![image](https://user-images.githubusercontent.com/6239286/93212290-fd976780-f794-11ea-9673-adfb474e4c9f.png)

4.目前是否支持通过线条删除或者节点删除 ,比如选中后使用delete快捷键删除

**哪个butterfly版本在哪个浏览器／操作系统发生的错误？**

"butterfly-dag": "^2.8.32"
chrome浏览器

**请重现步骤，如果可以的话，请提供一个最小的演示案例。**

demo地址:  https://github.com/caopanwei/bufferfly-vuedemo.git

**Comment by noonnightstorm** [comment]
第一个问题，因为线段太细了，导致了不容易点击，有一个isExpandWidth的属性可以支持更好的体验，但主要事件响应需要使用eventHandlerDom，具体可以看线段的文档

**Comment by noonnightstorm** [comment]
第二个问题这边比较少出现，一般是比较卡的问题或者使用不当导致比较卡才会飘逸出去的，这部分我看能不能优化。但性能问题的话我需要和你一起看看

**Comment by noonnightstorm** [comment]
第三个问题没看懂耶，可以详细描述下么？

**Comment by noonnightstorm** [comment]
第四点是支持的，但需要你自己去监听事件和自己调用节点和线段的删除事件

**Comment by caopanwei** [comment]
多谢,其他问题我再研究下
第三个问题,我截图了,麻烦您看下
https://gitee.com/cpw/Imgserver2/raw/master/img/20200915211125.png

**Comment by noonnightstorm** [comment]
我明白你的第三个问题了。你可以在this.canvas.theme.edge里面配置属性，这个配置是默认所有线段的样式。而你在单条edge上配置的属性仅仅会对当前线段生效
