### ISSUE TITLE
全局theme.endpoint.limitNum不生效问题

### ISSUE THREAD

**Issue by caopanwei** [alibaba/butterfly#355]
**您想申请的是需求还是问题？**
问题
**目前的情况是什么？**
全局的theme.endpoint.limitNum不生效问题 ,发现源码没有获取limitNum的值
![image](https://user-images.githubusercontent.com/6239286/93313225-ca0f1880-f83a-11ea-9b83-73012bfe6988.png)

**预期的结果是什么？**

**哪个butterfly版本在哪个浏览器／操作系统发生的错误？**
2.8.32
chrome
**请重现步骤，如果可以的话，请提供一个最小的演示案例。**
https://github.com/caopanwei/bufferfly-vuedemo.git

**Comment by noonnightstorm** [comment]
很抱歉，可能之前遗漏了，请问方便提个pr上来么？
