### ISSUE TITLE
自定义Node后, 自定义dom按钮的onclick如何能触发vue的method中弹出表单编辑页面

### ISSUE THREAD

**Issue by caopanwei** [alibaba/butterfly#357]
**您想申请的是需求还是问题？**
需求
**目前的情况是什么？**

使用的vue项目,demo在下方有链接

1.自定义Node后, 自定义dom按钮的onclick如何能触发vue的method中弹出表单编辑页面呢,目前不太清楚怎么触发?
节点格式如下图
![image](https://user-images.githubusercontent.com/6239286/93344937-d9a35700-f864-11ea-8aea-d8b77fd4337b.png)

**预期的结果是什么？**

前端小白,麻烦指点下如何实现以上的功能

**哪个butterfly版本在哪个浏览器／操作系统发生的错误？**

2.8.32
chrome

**请重现步骤，如果可以的话，请提供一个最小的演示案例。**
https://github.com/caopanwei/bufferfly-vuedemo.git

**Comment by noonnightstorm** [comment]
有this.canvas.on的事件机制，当点击事件的时候会抛出node:click的事件，你监听到的时候使用征程vue方式打开即可

**Comment by caopanwei** [comment]
好的,多谢
