### ISSUE TITLE
是否变量命名需要name convention下

### ISSUE THREAD

**Issue by jeffmobiles** [alibaba/butterfly#364]
**您想申请的是需求还是问题？**
gridService里的
backgroud 是background的意思吗,  
circleRadiu是circleRadius吗

**目前的情况是什么？**

**预期的结果是什么？**

**哪个butterfly版本在哪个浏览器／操作系统发生的错误？**

**请重现步骤，如果可以的话，请提供一个最小的演示案例。**

**Comment by jeffmobiles** [comment]
到此一游。

**Comment by jeffmobiles** [comment]
- 很好的编辑库。

**Comment by jeffmobiles** [comment]
给团队一个赞。 这个小问题请忽略掉.

**Comment by noonnightstorm** [comment]
谢谢，这些拼写错误我们会尽快检查
