### ISSUE TITLE
生成画布那里代码不对吧，这样写会报错啊，require那一行代码

### ISSUE THREAD

**Issue by ashi7** [alibaba/butterfly#366]
**您想申请的是需求还是问题？**

**目前的情况是什么？**

**预期的结果是什么？**

**哪个butterfly版本在哪个浏览器／操作系统发生的错误？**

**请重现步骤，如果可以的话，请提供一个最小的演示案例。**

**Comment by noonnightstorm** [comment]
麻烦把问题详细描述下，对应是哪个文件哪一行？
