### ISSUE TITLE
demo移植报错

### ISSUE THREAD

**Issue by baikaifa** [alibaba/butterfly#367]
为什么我把官网的例子弄过来会报错啊，我是把run-tree整个文件夹复制过来，并且把里面的引用改成
官方提示的
import {Canvas, Group, Edge} from 'butterfly-dag';
import 'butterfly-dag/dist/index.css';
但是接下来就报错了，修复一个，还有一个。
希望官方能出个类似于G6的那种文档，有直接可以运行的demo，虽然现在也有demo，但是都是以来的内部文件，希望有那种类似我上面引用的那种demo，因为要用的话肯定是上面那种方式啊。

**Comment by noonnightstorm** [comment]
其实将demo的小蝴蝶引用路径修改下即可，逻辑都是经过很多产品验证的，只是路径现在是源码引用方便大家调试。
