### ISSUE TITLE
Question: Is it possible to add connections between nodes like in draw.io?

### ISSUE THREAD

**Issue by fatihky** [alibaba/butterfly#373]
(here I'm using google translate results for questions)

**Do you want to apply for a demand or a problem? **
question

**What is the current situation? **
I couldn't see in the demos.

**What is the expected result? **
Ability to add connections between nodes.

**Which butterfly version does the error occur in which browser/operating system? **
none

**Please reproduce the steps, and if possible, please provide a minimal demonstration case. **
I'm using the curent latest version: `2.8.43`

Hi. I wonder if I can create connection between nodes dynamically. I mean like in draw.io, n8n or other alternatives.

**Comment by noonnightstorm** [comment]
Yes, it is . You can see "Force" demo which is add connections between nodes . You can see Edge API . 'type' params :https://github.com/alibaba/butterfly/blob/master/docs/en-US/edge.md#attribute

**Comment by fatihky** [comment]
Hi @noonnightstorm, thank you for your reply. It seems `canvas.draw` creates connections programmatically. It can be useful, but, actually, I meant something different. Sorry I couldn't express my request well. Here is a gif that shows exactly what I want to accomplish:

![2020-10-23 01 38 48](https://user-images.githubusercontent.com/4169772/96937400-b0fc2600-14d0-11eb-99d0-49b58549f8c2.gif)

Is that possible with this library?

**Comment by noonnightstorm** [comment]
Of course  . I wiil write a demo in butterfly example next week .

**Comment by Andrew3005** [comment]
https://github.com/alibaba/butterfly/issues/373#issuecomment-714895197
any updates?

**Comment by Andrew3005** [comment]
@noonnightstorm and can you put example of `undo/redo` functions?

**Comment by fatihky** [comment]
> [#373 (comment)](https://github.com/alibaba/butterfly/issues/373#issuecomment-714895197)
> any updates?

@Andrew3005 it seems my issue has been resolved by the `compactBoxTree` example. It allows connections to be made dynamically.

> @noonnightstorm and can you put example of `undo/redo` functions?
I think it would be better to open a new issue as your request doesn't seem in the scope of this issue. What do you think?

**Comment by Andrew3005** [comment]
@noonnightstorm got it, thanks

sure, I will open new issue, thanks!

**Comment by fatihky** [comment]
@Andrew3005 thank you for your understanding!

@noonnightstorm thank you so much for this library and resolving this issue.
