### ISSUE TITLE
如何不让node移到goup外面区域

### ISSUE THREAD

**Issue by wychl** [alibaba/butterfly#375]
**您想申请的是需求还是问题？**
需求

**目前的情况是什么？**
不支持

**预期的结果是什么？**
- 不让node拖拽到goup外面区域，一直在group内 。
- group区域大小减少时，让node一直待在group内。

**哪个butterfly版本在哪个浏览器／操作系统发生的错误？**
**请重现步骤，如果可以的话，请提供一个最小的演示案例。**

**Comment by noonnightstorm** [comment]
这个现在暂时不支持，需要的话我可以支持下。

**Comment by wychl** [comment]
非常感谢，能先提供下思路吗？

**Comment by noonnightstorm** [comment]
就是我会提供一个参数，然后控制node不能移动出group那

**Comment by noonnightstorm** [comment]
butterfly-dag@2.8.47 , https://github.com/alibaba/butterfly/blob/master/docs/zh-CN/canvas.md#canvas-attr ， 请看看theme.group.type的属性，或者在group的type属性上赋值，文档上都有

**Comment by wychl** [comment]
谢谢
