### ISSUE TITLE
滚动条bug

### ISSUE THREAD

**Issue by Zt448143356** [alibaba/butterfly#382]
**您想申请的是需求还是问题？**

问题

**目前的情况是什么？**

滑动滚动条，线出现的位置与鼠标不重合。

**预期的结果是什么？**

线出现位置与鼠标重合

**哪个butterfly版本在哪个浏览器／操作系统发生的错误？**

butterfly@2.5.15及butterfly@2.8.49。
Chrome版本 87.0.4280.67（正式版本） (x86_64)。

**请重现步骤，如果可以的话，请提供一个最小的演示案例。**

滑动滚动条即可出现连线点与鼠标位置存在偏差

**Comment by noonnightstorm** [comment]
已知bug，我尽快修复

**Comment by noonnightstorm** [comment]
2.8.x及以上已解决
