### ISSUE TITLE
有现成的工具条组件吗

### ISSUE THREAD

**Issue by southpush** [alibaba/butterfly#401]
**您想申请的是需求还是问题？**
问题

**目前的情况是什么？**
我在网上看到butterfly-dag的一篇文章，我想问问里面的这张图的效果是怎么做出来的，有工具条的组件直接使用吗，还是需要自己写一个工具条

![image](https://user-images.githubusercontent.com/33292427/102292550-55a25d80-3f80-11eb-8ddc-547491b910d4.png)

然后还有那种拖拽一个画布外的节点增加到画布中的功能，大概需要怎么做出来呢？我看文档好像没看到相关的

**Comment by noonnightstorm** [comment]
拖拽节点画布的话，这个是需要使用第三方组件react-dnd的。工具栏也是需要自己写的。小蝴蝶只关注于画布中间

**Comment by noonnightstorm** [comment]
不过后续小蝴蝶有可能会出editor，到时候是会有左中右结构
