### ISSUE TITLE
demo的login例子,浏览器控制台报错

### ISSUE THREAD

**Issue by niaoqq1** [alibaba/butterfly#403]
**您想申请的是需求还是问题？**
问题
**目前的情况是什么？**
demo的login例子，拖动node时，谷歌浏览器console中报错
**预期的结果是什么？**
不报错
**哪个butterfly版本在哪个浏览器／操作系统发生的错误？**
butterfly版本3.0.19，谷歌浏览器版本87.0.4280.88
**请重现步骤，如果可以的话，请提供一个最小的演示案例。**
![image](https://user-images.githubusercontent.com/44127471/102679028-70c2d680-41e7-11eb-9578-fab8e883ade9.png)
![image](https://user-images.githubusercontent.com/44127471/102679051-8cc67800-41e7-11eb-9d0b-9a67975259e7.png)

**Comment by noonnightstorm** [comment]
请更新一下代码，昨天修复了，#402
