### ISSUE TITLE
react版本无法判断是否可以连线，画布上直接就连上了

### ISSUE THREAD

**Issue by wangbin-coder** [alibaba/butterfly#428]
**您想申请的是需求还是问题？**
需求
**目前的情况是什么？**
react版本无法判断是否可以连线，画布上直接就连上了
**预期的结果是什么？**
可以判断是否可以连线，再在画布上连线
**哪个butterfly版本在哪个浏览器／操作系统发生的错误？**

**请重现步骤，如果可以的话，请提供一个最小的演示案例。**

**Comment by noonnightstorm** [comment]
@cctv1005s 帮忙看看
