### ISSUE TITLE
Unusual node behavior with Vue implementation

### ISSUE THREAD

**Issue by BlackFireAlex** [alibaba/butterfly#431]
I have trouble with a seemingly invisible wall that makes my nodes behaves strangely here are some pictures to show the issue:

Issue 1 when moving outside of this invisible wall: 
![InkedCapture d’écran 2021-01-24 163451_LI](https://user-images.githubusercontent.com/8484750/105635482-4528b100-5e63-11eb-913c-d87e622b28f7.jpg)
![Capture d’écran 2021-01-24 163505](https://user-images.githubusercontent.com/8484750/105635311-705ed080-5e62-11eb-9796-f5de44298d9a.jpg)
![Capture d’écran 2021-01-24 163516](https://user-images.githubusercontent.com/8484750/105635312-705ed080-5e62-11eb-9856-36c457e62ea7.jpg)

Issue 2:
![Capture d’écran 2021-01-24 163631](https://user-images.githubusercontent.com/8484750/105635313-70f76700-5e62-11eb-9a66-82222e12dc69.jpg)

I am currently using the vue implementation as you can see there seem to be an invisible line that makes my nodes shrink and links disconnect.

This is my canvas conf

```javascript
const defaultOptions = {
    disLinkable: true, // enable disConnect edges
    linkable: true, // enable connect edges
    draggable: true, // enable drag nodes
    zoomable: true, // enable zoom canvas
    layout: {
        type: 'forceLayout',
        options: {
            link: {
                // 线条的距离
                distance: 1800,
                // 线条的粗细
                strength: 3
            }
        },
    },
    autoFixCanvas: {     // auto expand canvas when drag nodes or edges near the edge of canvas.
        enable: true,
        autoMovePadding: [20, 20, 20, 20]
    },
    autoResizeRootSize: true // automatically adapt to the root size, the default is true
    ,
    moveable: true, // enable move canvas
    theme: {
        edge: {
            arrow: true,
            type: 'AdvancedBezier',
            defaultAnimate: false
        }
    }
};```

**Comment by noonnightstorm** [comment]
@Zt448143356

**Comment by Zt448143356** [comment]
Issue 1: Occurs when the width of the node is text spread,Now You need to give the node a width(css style).We will try to fix this problem。
Issue 2: Occurs when type: 'forcelayout'.(now It's too late, Continue next time)

**Comment by BlackFireAlex** [comment]
Okay thanks I have fixed it by settings a width, the second issue is gone too although i didn't understand what you said about it. Thanks anyway !

**Comment by BlackFireAlex** [comment]
@Zt448143356 Also when I try to update the canvas with ```
      this.$children[0].canvas.redraw(mockData2,()=>console.log("End"))
      ```

I get this error and only edges show up
```
Uncaught TypeError: Cannot read property 'sourceEndpoint' of undefined
    at VueComponent.onCreateEdge (index.js?4a74:1)
    at _.eval (index.js?4a74:1)
    at _.u.emit (index.js?995b:formatted:14884)
    at _.value (index.js?995b:formatted:3373)
    at eval (index.js?995b:formatted:3013)```

**Comment by Zt448143356** [comment]
sorry, now, redraw function of Vue version is not supported.I will support it in future versions。

now, if you need redraw canvas,you can Clear canvasData,and then add data to the canvasData again.
(The canvas changes as the canvasData changes)

like
```
this.mockData = {};

this.$nextTick(()=>{
  this.mockData = mockData1;
})
```

not
```
this.mockData = {};
this.mockData = mockData1;

//or

this.mockData = mockData1
```
Because diff is based on id,When mockData has the same id as mockData1, Canvas will not redraw the graph(node,edge,group) of this ID.We need to wait for `this.mockData = {};` to end before add data to avoid this problem.

**Comment by Zt448143356** [comment]
> I have trouble with a seemingly invisible wall that makes my nodes behaves strangely here are some pictures to show the issue:
> 
> Issue 1 when moving outside of this invisible wall:
> ![InkedCapture d’écran 2021-01-24 163451_LI](https://user-images.githubusercontent.com/8484750/105635482-4528b100-5e63-11eb-913c-d87e622b28f7.jpg)
> ![Capture d’écran 2021-01-24 163505](https://user-images.githubusercontent.com/8484750/105635311-705ed080-5e62-11eb-9796-f5de44298d9a.jpg)
> ![Capture d’écran 2021-01-24 163516](https://user-images.githubusercontent.com/8484750/105635312-705ed080-5e62-11eb-9856-36c457e62ea7.jpg)
> 
> Issue 2:
> ![Capture d’écran 2021-01-24 163631](https://user-images.githubusercontent.com/8484750/105635313-70f76700-5e62-11eb-9a66-82222e12dc69.jpg)
> 
> I am currently using the vue implementation as you can see there seem to be an invisible line that makes my nodes shrink and links disconnect.
> 
> This is my canvas conf
> 
> ```js
> const defaultOptions = {
>     disLinkable: true, // enable disConnect edges
>     linkable: true, // enable connect edges
>     draggable: true, // enable drag nodes
>     zoomable: true, // enable zoom canvas
>     layout: {
>         type: 'forceLayout',
>         options: {
>             link: {
>                 // 线条的距离
>                 distance: 1800,
>                 // 线条的粗细
>                 strength: 3
>             }
>         },
>     },
>     autoFixCanvas: {     // auto expand canvas when drag nodes or edges near the edge of canvas.
>         enable: true,
>         autoMovePadding: [20, 20, 20, 20]
>     },
>     autoResizeRootSize: true // automatically adapt to the root size, the default is true
>     ,
>     moveable: true, // enable move canvas
>     theme: {
>         edge: {
>             arrow: true,
>             type: 'AdvancedBezier',
>             defaultAnimate: false
>         }
>     }
> };```
> ```

There is a problem with your canvas conf
```
const defaultOptions = {
    disLinkable: true, // enable disConnect edges
    linkable: true, // enable connect edges
    draggable: true, // enable drag nodes
    zoomable: true, // enable zoom canvas
    layout: {
        type: 'forceLayout',
        options: {
            link: {
                // 线条的距离
                distance: 1800,
                // 线条的粗细
                strength: 3
            }
        },
    },
    autoResizeRootSize: true, // automatically adapt to the root size, the default is true
    moveable: true, // enable move canvas
    theme: {
        edge: {
            arrow: true,
            type: 'AdvancedBezier',
            defaultAnimate: false
        },
        autoFixCanvas: {     // auto expand canvas when drag nodes or edges near the edge of canvas.
            enable: true,
            autoMovePadding: [20, 20, 20, 20]
        },
    }
}; 
```
`autoFixCanvas`should be in`theme`

**Comment by BlackFireAlex** [comment]
Okay the update is working great with what you said thanks, waiting for everything to work with vue this product is awesome
