### ISSUE TITLE
vue版本能否支持vnode渲染？

### ISSUE THREAD

**Issue by zcmk123** [alibaba/butterfly#441]
预期的结果是什么？**
vue版本能否支持vnode渲染？
能不能不用runtime compiler 直接支持渲染vnode呢

**Comment by noonnightstorm** [comment]
@Zt448143356 有空可以帮忙看看

**Comment by zcmk123** [comment]
[https://github.com/alibaba/butterfly/blob/bd911c3b1f1374199a94b55c1b5af356f9ac677d/vue/coms/Vue-node.vue#L24](url)
我看这里是用template渲染的，貌似应该改成render函数渲染就可以支持vnode

**Comment by Zt448143356** [comment]
当前使用的template渲染，主要是因为有很大的一部分Vue的用户不会使用render函数。只会使用template模板。为了对新手更加友好。所以就采取了当前的方案。
后续可能会提供多个版本供用户选择。template和render两种版本。暂未添加入计划，仅是当前您的issues为我提供的想法。

**Comment by zcmk123** [comment]
> 当前使用的template渲染，主要是因为有很大的一部分Vue的用户不会使用render函数。只会使用template模板。为了对新手更加友好。所以就采取了当前的方案。
> 后续可能会提供多个版本供用户选择。template和render两种版本。暂未添加入计划，仅是当前您的issues为我提供的想法。

感谢。。希望尽快支持，我先自己改来用吧

**Comment by Zt448143356** [comment]
你可以加入我们，fork分支一起开发为社区做贡献。去完善你当前提出的想法。

**Comment by zcmk123** [comment]
> 你可以加入我们，fork分支一起开发为社区做贡献。去完善你当前提出的想法。

谢谢，我先改一下，等周末有空可以提一下pr
