### ISSUE TITLE
node属性 class 应为小写

### ISSUE THREAD

**Issue by blueken** [alibaba/butterfly#452]
**您想申请的是需求还是问题？**

**目前的情况是什么？**
大写Class报错
index.js:2 Uncaught TypeError: Cannot define property jQuery3510385411901136159861, object is not extensible
**预期的结果是什么？**

**哪个butterfly版本在哪个浏览器／操作系统发生的错误？**

**请重现步骤，如果可以的话，请提供一个最小的演示案例。**

**Comment by noonnightstorm** [comment]
请提供最小复现的代码
