### ISSUE TITLE
表字段血缘/业务血缘的demo什么时候能开源？

### ISSUE THREAD

**Issue by zhouzhenxxxx** [alibaba/butterfly#480]
会有vue版本吗

**Comment by noonnightstorm** [comment]
你这边比较着急么？血缘组件我们已经内测很久了。只是想等butterfly-editor一起开源掉。vue版本暂时不支持，我们可能稍微才会支持

**Comment by zhouzhenxxxx** [comment]
比较着急，但是我们这边项目是用vue版本。暂时不支持vue的话就算了，谢谢。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月15日(星期一) 下午2:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/butterfly] 表字段血缘/业务血缘的demo什么时候能开源？ (#480)





 
你这边比较着急么？血缘组件我们已经内测很久了。只是想等butterfly-editor一起开源掉。vue版本暂时不支持，我们可能稍微才会支持

**Comment by noonnightstorm** [comment]
可能近一周都没办法开源掉vue组件的，抱歉

**Comment by wsxe9988** [comment]
vue3计划支持嘛

**Comment by difty** [comment]
能提供react版本吗，可以自己改写成 vue 的 @noonnightstorm

**Comment by noonnightstorm** [comment]
> 能提供react版本吗，可以自己改写成 vue 的 @noonnightstorm

这两天可以，主要在走流程

**Comment by noonnightstorm** [comment]
已开源：https://github.com/aliyun/react-lineage-dag
