### ISSUE TITLE
给如此优秀的项目点赞，附一个小问题

### ISSUE THREAD

**Issue by qdore** [alibaba/butterfly#481]
请问如下的图片，对应的demo，有吗，找了example，但是木有类似的例子

![image](https://user-images.githubusercontent.com/6831829/111115601-cff27600-859f-11eb-99a6-d56e5689b3a7.png)

**Comment by noonnightstorm** [comment]
这个是咱们内的业务应用，由于不能对外，所以不能封装出来，望理解

**Comment by noonnightstorm** [comment]
这个也是基于小蝴蝶来封装的

**Comment by qdore** [comment]
明白~  谢谢，我close掉这个issue
