### ISSUE TITLE
是否支持，在鼠标悬浮node时，对应的endpoint才显现，默认不显示

### ISSUE THREAD

**Issue by qdore** [alibaba/butterfly#482]
业务场景有这个需求，咨询一下是否直接就可以支持~

**Comment by noonnightstorm** [comment]
这个支持啊，请问你使用是自定义的endpoint还是系统自带的？假如是自定义的话，你自己hover node的时候把endpoint的visibility设置下即可。假如是系统的，你可以在node的类里面绑定mouseover时间，this.endpoints里面能取到endpoint的数据和dom

**Comment by noonnightstorm** [comment]
切记隐藏endpoint只能设置visibility，不能设置display:none。不然我锚点位置计算不出来

**Comment by qdore** [comment]
好滴~ 谢谢

**Comment by noonnightstorm** [comment]
你可以加钉钉群：32508327，这样答疑会更快

**Comment by qdore** [comment]
好滴 谢谢~
