### ISSUE TITLE
autoFixCanvas does not work (vue)

### ISSUE THREAD

**Issue by manishpatelUK** [alibaba/butterfly#489]
## The current behavior
When we set autoFixCanvas, the canvas should expand automatically. 

## The expected behavior
Canvas should expand

## Your environment(such as: Butterfly version、Browser version、OS and so on)

`Butterfly version`: 3.2.5 
`butterfly-vue`: 0.0.5

`Browser version`: 89.0.4389.90 (Official Build) (64-bit)

`OS`: Windows 10

## Steps To Reproduce, Maybe you can provide a simple demo.
Run below.

	<template>
	  <butterfly-vue ref="butterfly"
		  :canvasData="graphData"
		  @onLoaded="onLoaded">

	  </butterfly-vue>
	</template>

	<script>
	import ButterflyVue from 'butterfly-vue'
	import 'butterfly-vue/index.css'
	import _ from "lodash";

	// eslint-disable-next-line no-unused-vars
	const endpoints = [
		{
		id: 'right',
		orientation: [1, 0],
		pos: [0, 0.5]
		},
		{
		  id: 'left',
		  orientation: [-1, 0],
		  pos: [0, 0.5]
		}
	]

	export default {
	  name: "WorkflowChart",
	  components: {
		ButterflyVue
	  },
	  props: {
		workflow: {
		  type: Object
		}
	  },
	  data () {
		return {
		  graphData: {
			groups: [],
			nodes: [],
			edges: [],
		  }
		}
	  },
	  created() {
		this.reconstitute()
	  },
	  methods: {
		onLoaded: function (canvas) {
		  console.log(canvas)
		  canvas.theme = {                 // theme (optional)
			group: {
			  type: 'normal'       // Node group type: normal (drag in and drag out), inner (can only be dragged in and not out)
			},
			edge: {
			  type: 'Bezier',      // edge type：Bezier curve，Polyline ，Straight，Manhattan line，Improved Bezier curve。values ： Bezier/Flow/Straight/Manhattan/AdvancedBezier
			  label: 'test',       // edge label
			  arrow: true,         // whether to show arrow
			  arrowPosition: 0.5,  // arrow position (0 ~ 1)
			  arrowOffset: 0.0,    // arrow offset
			  isExpandWidth: false,// expand line interaction area
			  defaultAnimate: false// turn on line animation by default
			},
			endpoint: {
			  position: [],        // limit endpoint position ['Top', 'Bottom', 'Left', 'Right'],
			  linkableHighlight: true,// point.linkable method is triggered when connecting, can be highlighted
			  limitNum: 10,        // limit the number of anchor connections
			  expandArea: {        // when the anchor point is too small, the connection hot zone can be expanded.
				left: 10,
				right: 10,
				top: 10,
				bottom: 10
			  }
			},
			zoomGap: 0.001,       // mouse zoom in and out gap settings
			autoFixCanvas: {     // auto expand canvas when drag nodes or edges near the edge of canvas.
			  enable: true,
			  autoMovePadding: [20, 20, 20, 20]
			},
			autoResizeRootSize: true // automatically adapt to the root size, the default is true
		  }
		  canvas.layout= {type: 'dagreLayout', options:{rankdir:'TB', nodestep:40, rankstep:40, controlPoints: false}}
		  canvas.relayout()

		},

		reconstitute: function () {
		  console.log("add data now")
		  this.graphData.groups.splice(0)
		  this.graphData.nodes.splice(0)
		  this.graphData.edges.splice(0)
		  let drawn = []

		  // add all the nodes fist
		  this.workflow.elements.forEach(element => {
			if (!drawn.includes(element.graphId)) {
			  this.graphData.nodes.push(
				  {
					id: element.graphId,
					endpoints: endpoints
				  })
			  drawn.push(element.graphId)
			}
		  })

		  //add the arcs

		  this.workflow.elements.forEach(element => {
			_.get(element, 'children', []).forEach(child => {
			  this.graphData.edges.push({
				id: element.graphId + "-" + child,
				sourceNode: element.graphId,
				targetNode: child,
				source: 'right',
				target: 'left'
			  })
			})
		  })
		},
	  }
	}
	</script>

	<style scoped>

	</style>

**Comment by noonnightstorm** [comment]
@Zt448143356

**Comment by Zt448143356** [comment]
Sorry, there are no simple demo available for the time being.However, I can answer your doubts.Simple demo will probably released in June。

**I used Element-UI in this mockData**，You can replace this part.
```js
// mockData.js
const endpoints = [{
  id: 'right',
  orientation: [1, 0],
  pos: [0, 0.5]
},
{
  id: 'left',
  orientation: [-1, 0],
  pos: [0, 0.5]
}
];

export default {
groups: [{
  id: '1',
  left: 10,
  top: 100,
  render: `<div :style="{width:'250px',textAlign:'center',backgroundColor:'blanchedalmond'}" class='group-style'>testgroup</div>`
}],
nodes: [{
    id: '1',
    group: '1',
    // top: 50,
    // left: 300,
    endpoints: endpoints,
    render: `<el-button type="primary">node1</el-button>`
  },
  {
    id: '2',
    top: 25,
    left: 300,
    endpoints: endpoints,
    render: `<div :style="{width:'150px'}">node2</div>`
  },
  {
    id: '3',
    top: 25,
    left: 600,
    endpoints: endpoints,
  }
],
edges: [{
  id: '1-2',
  sourceNode: '1',
  targetNode: '2',
  source: 'right',
  target: 'left',
  render: '<div>test label</div>'
}],
};
```

``` vue
<template>
  <div id="app">
    <butterfly-vue
      ref="butterfly"
      :canvasData="mockData"
      :canvasConf="Conf"
      @onCreateEdge="logEvent"
      @onChangeEdges="logEvent"
      @onDeleteEdge="logEvent"
      @onLoaded="finishLoaded"
    />
  </div>
</template>

<script>
import ButterflyVue from 'butterfly-vue';
import "butterfly-vue/index.css";
import mockData from "./mockData";

export default {
  name: "App",
  components: {
    ButterflyVue,
  },
  data() {
    return {
      mockData,
      Conf: {
        disLinkable: true, // enable disConnect edges
        linkable: true, // enable connect edges
        draggable: true, // enable drag nodes
        zoomable: true, // enable zoom canvas
        layout: {
          type: 'dagreLayout',
          options:{
            rankdir:'TB',
            nodestep:40,
            rankstep:40,
            controlPoints: false
          }
        },
        autoResizeRootSize: true, // automatically adapt to the root size, the default is true
        moveable: true, // enable move canvas
        theme: {
          group: {
            type: 'normal'       // Node group type: normal (drag in and drag out), inner (can only be dragged in and not out)
          },
          edge: {
            type: 'Bezier',      // edge type：Bezier curve，Polyline ，Straight，Manhattan line，Improved Bezier curve。values ： Bezier/Flow/Straight/Manhattan/AdvancedBezier
            label: 'test',       // edge label
            arrow: true,         // whether to show arrow
            arrowPosition: 0.5,  // arrow position (0 ~ 1)
            arrowOffset: 0.0,    // arrow offset
            isExpandWidth: false,// expand line interaction area
            defaultAnimate: false// turn on line animation by default
          },
          endpoint: {
            position: [],        // limit endpoint position ['Top', 'Bottom', 'Left', 'Right'],
            linkableHighlight: true,// point.linkable method is triggered when connecting, can be highlighted
            limitNum: 10,        // limit the number of anchor connections
            expandArea: {        // when the anchor point is too small, the connection hot zone can be expanded.
            left: 10,
            right: 10,
            top: 10,
            bottom: 10
            }
          },
          zoomGap: 0.001,       // mouse zoom in and out gap settings
          autoFixCanvas: {     // auto expand canvas when drag nodes or edges near the edge of canvas.
            enable: true,
            autoMovePadding: [20, 20, 20, 20]
          },
          autoResizeRootSize: true // automatically adapt to the root size, the default is true
        },
      },
    };
  },
  methods: {
    logEvent(e) {
      console.log(e);
    },
    finishLoaded(canvans) {
      console.log(canvans);
      console.log("finish");
    },
  },
};
</script>
```
![4](https://user-images.githubusercontent.com/48010552/113371999-33e7ad80-939a-11eb-9cfa-286d50c55291.gif)
Is this what you want?

**Comment by manishpatelUK** [comment]
Aha thanks @Zt448143356 - I completely missed the fact that `canvasConf` is a prop.

Can you show me how you included `element-ui` please? I'm using `Vuetify`. But I don't see where/how the component library or its css comes into play here.

**Comment by manishpatelUK** [comment]
Ignore the above message - rebuild/refresh fixed it after this. Thanks!

**Comment by Zt448143356** [comment]
in main.js
``` js
// main.js
import Vue from 'vue';
import ElementUI from 'element-ui';
import 'element-ui/lib/theme-chalk/index.css';
import App from './App.vue';

Vue.use(ElementUI);

new Vue({
  render: h => h(App),
}).$mount('#app')
```

![image](https://user-images.githubusercontent.com/48010552/113390188-cfd9df00-93c3-11eb-975e-0e2e6bbdae90.png)
Is this what you want?Did I explain it clearly?

**Comment by manishpatelUK** [comment]
Yes, thanks. Oddly the same does not work with Vuetify but that is ok.. can just just use `div` with classes
