### ISSUE TITLE
butterfly-react version question

### ISSUE THREAD

**Issue by kachanovskiy** [alibaba/butterfly#497]
## The current behavior

npm reports version 0.0.23-beta (for package https://www.npmjs.com/package/butterfly-react), package.json under /react says it is 0.0.10-beta. hence it is not clear which version is the right one.

## The expected behavior
If the packet is published to npm, the version on npm should be the same as in source code.

**Comment by noonnightstorm** [comment]
@cctv1005s

**Comment by cctv1005s** [comment]
@kachanovskiy 
It's hard to merge latest react version to master branch for the reason that  merge of  this [PR](https://github.com/alibaba/butterfly/pull/460) has been delay.

I have do something on react-version base on this PR. If you want to read the latest code of react, this [branch](https://github.com/cctv1005s/butterfly/tree/feat/react/react) can help you.

**Comment by kachanovskiy** [comment]
thanks for clarifying this. so, as far as i understand, butterfly-react releases from that branch?

any chance it is going to be merged any soon so that we don't have to build manually or jump between repos to read the code?

**Comment by cctv1005s** [comment]
@kachanovskiy 
Before the end of this month.

**Comment by kachanovskiy** [comment]
thank you, i consider the issue resolved. awaiting for merge! :)
