### ISSUE TITLE
vue版本是不是class没支持

### ISSUE THREAD

**Issue by lonelyzou** [alibaba/butterfly#521]
在nodes和edges配置class，但是不生效

**Comment by noonnightstorm** [comment]
@Zt448143356

**Comment by Zt448143356** [comment]
是的。Vue版本不支持class。
用class就直接上原生好了呀。
[0.1.0](https://github.com/alibaba/butterfly/issues/496#issuecomment-826272351)版本的一些变更
vue版本最新是0.1.0版本。还是不太稳定的版本。可能还会出现大改动。
[example](https://github.com/Zt448143356/butterfly/tree/master/vue)文件夹是当前vue版本的demo。
vue版本主要是支持了数据驱动。（重要项目建议使用原生版本。因为原生版本、react版本相对稳定。Vue版本还未趋于稳定、bug等还比较多）
