### ISSUE TITLE
自定义节点信息如何更新？

### ISSUE THREAD

**Issue by funs-scaler** [alibaba/butterfly#564]
请问一下，自定义节点，根据节点里的信息来渲染节点内容，当信息更新时，我需要怎么使节点更新，难道要使用redraw?

**Comment by noonnightstorm** [comment]
1: 在原生小蝴蝶里面，这个如何变化是依靠业务方判断，自己拓展方法来更新，自己操作dom来更变
2: 假如需要数据驱动的话，就使用react butterfly / vue butterfly来对数据进行双向绑定

**Comment by funs-scaler** [comment]
好的。感谢
