### ISSUE TITLE
setGridMode网格背景颜色设置不成功

### ISSUE THREAD

**Issue by huyongyong1992** [alibaba/butterfly#575]
```
this.canvas.draw(this.mockData, () => {
          console.log('1:', canvas.setGridMode);
          canvas.setGridMode(true, {
            isAdsorb: false,
            theme: {
              shapeType: 'circle',
              gap: 40,

              background: '#ff00ff', // 网格背景颜色
              circleRadiu: 1,
              circleColor: '#999', // 圆点颜色
            },
          });
        });
```
## The current behavior

![image](https://user-images.githubusercontent.com/22605989/120603694-db5a8c80-c47e-11eb-9c19-32e77bc1dad4.png)

## The expected behavior

没有出现https://butterfly-dag.gitee.io/butterfly-dag/demo/liteGraph中的效果

开始以为backgroud单词写错了，改成background也不行
在源码处 https://github.com/alibaba/butterfly/blob/4cb5b183da375d4930e3a0cc332927a2e6ed335e/src/canvas/baseCanvas.js#L3865 没看懂网格相关的设置
## Your environment(such as: Butterfly version、Browser version、OS and so on)

`Butterfly version`: v4.0.6

`Browser version`: chrome

`OS`:  mac M1

**Comment by noonnightstorm** [comment]
好的，收到，我今晚修复一下

**Comment by huyongyong1992** [comment]
详细阅读源码后发现 https://github.com/alibaba/butterfly/blob/4cb5b183da375d4930e3a0cc332927a2e6ed335e/src/utils/gridService.js 中createCircle并没有设置background...

**Comment by noonnightstorm** [comment]
好的，感谢，最好能提一个pr，假如不急的话我今晚修复下。白天比较忙，哈哈～

**Comment by huyongyong1992** [comment]
> 好的，感谢，最好能提一个pr，假如不急的话我今晚修复下。白天比较忙，哈哈～

嗯嗯，不急

**Comment by noonnightstorm** [comment]
butterfly-dag@4.0.7已修复
