### ISSUE TITLE
addEndpoint 中pos属性设置无效

### ISSUE THREAD

**Issue by funs-scaler** [alibaba/butterfly#576]
## The current behavior

```
node.addEndpoint({
    id: 'test-id',
    orientation: [0, -1],
    pos: [0.5, 0],
    type: 'source',
    dom: targetDom
})
连接点位置不会改变，始终都在Dom中心点位置
```
## The expected behavior

连接点位置改变，始终都在Dom上边线中心点位置

## Your environment(such as: Butterfly version、Browser version、OS and so on)

`Butterfly version`: 4.0.2

`Browser version`: chrome  90.0.4430.212

`OS`: mac

**Comment by noonnightstorm** [comment]
当你传入dom的话，你就不需要pos了，毕竟你dom可以自己控制位置。pos只生效于系统锚点

**Comment by funs-scaler** [comment]
感谢老铁，是我理解有误了
