### ISSUE TITLE
单击连线之后，会使画布有问题

### ISSUE THREAD

**Issue by funs-scaler** [alibaba/butterfly#578]
## The current behavior

单击连线之后，第一次点击画布不能触发system.canvas.click事件，并且不能拖动画布，要再点击一次才可以触发事件并拖动画布

## The expected behavior

单击连线之后，第一次点击画布就可以触发system.canvas.click事件，并且能拖动画布

## Your environment(such as: Butterfly version、Browser version、OS and so on)

`Butterfly version`:4.0.6

`Browser version`:91.0.4472.77

`OS`:mac os

## Steps To Reproduce, Maybe you can provide a simple demo.
 
可以在example decision示例中触发

**Comment by noonnightstorm** [comment]
好的，收到，我来看看

**Comment by noonnightstorm** [comment]
butterfly-dag@4.0.9已经修复
