### ISSUE TITLE
可以使用script标签的方式引入吗

### ISSUE THREAD

**Issue by qinhao3288** [alibaba/butterfly#593]
我们目前的项目前端是基于bootstrap+jquery ,   没有使用vue和react，请问我们怎么使用butterfly呢

**Comment by ManbasJi** [comment]
可以找个vue项目，npm install butterfly-dag，然后找到node_modules， 把butterfly-dag中的dist拷贝到本地用就行

**Comment by noonnightstorm** [comment]
可以的，你script引入后，我会在window下注入Butterfly的对象，里面都是画布，节点，线段的基类
