### ISSUE TITLE
可以在expandNode时进行node位置的改变吗

### ISSUE THREAD

**Issue by ManbasJi** [alibaba/butterfly#594]
我在Node类的draw方法中自定义了node的位置，但是一旦调用treeNode的收缩和展开，node位置就会复原。
想问下是否能够监听到expandNode函数，在expandNode执行时调整node的位置？

**Comment by noonnightstorm** [comment]
这个暂时不支持，因为展开和收起我都会重启计算位置的

**Comment by ManbasJi** [comment]
> 这个暂时不支持，因为展开和收起我都会重启计算位置的

**Comment by ManbasJi** [comment]
![微信截图_20210617152835](https://user-images.githubusercontent.com/20039217/122351862-24cbd100-cf81-11eb-9720-c5ad86b8ba39.png)


> 这个暂时不支持，因为展开和收起我都会重启计算位置的
请问这种布局可以单纯靠layout来实现吗（就是同时使用两种布局），我目前用的是compactbox，但是【指标维度】下方这些节点必须通过自定义位置才能这样摆放

**Comment by ManbasJi** [comment]
请问这种样式可以靠layout来实现吗（就是同时使用两种布局），我目前用的是compactbox，但是【指标维度】下方这些节点必须通过自定义位置才能这样摆放
![微信截图_20210617152835](https://user-images.githubusercontent.com/20039217/122352413-b1768f00-cf81-11eb-8568-86cecebb9c8e.png)
