### ISSUE TITLE
请问如何选中线段进行删除？

### ISSUE THREAD

**Issue by leeJie1994** [alibaba/butterfly#595]
现在移除连线是在锚点上进行操作的，但是当锚点上有多条连线时，只能按连接顺序进行移除，无法直接指定移除多条中的某一条，请问是否有方法直接选定连线进行移除？

**Comment by noonnightstorm** [comment]
可以，但这个只能由业务方来做，你点击连线的时候就能知道哪条线段，这时候你可以调用canvas.removeEdge来把线段删除掉
