### ISSUE TITLE
index.d.ts 中的内容不正确，控制台 Circular definition of import alias ...

### ISSUE THREAD

**Issue by gin-lsl** [alibaba/butterfly#596]
## The current behavior

使用 ts 开发的项目，引用 butterfly-dag 时控制台报错：
```
Circular definition of import alias 'Canvas'.
Circular definition of import alias 'TreeCanvas'.
......
```
如图：

![image](https://user-images.githubusercontent.com/18319675/122538574-45fff080-d059-11eb-939e-89f0a10f3294.png)

## Your environment(such as: Butterfly version、Browser version、OS and so on)

`Butterfly version`: 4.0.14

`TypeScript version`: ~4.3.2

**Comment by noonnightstorm** [comment]
好的，收到，估计之前升级导致的，我今晚修复下

**Comment by noonnightstorm** [comment]
butterfly-dag@4.0.19 , 我们暂时把d.ts文件去掉，后续我们会把小蝴蝶全部ts化

**Comment by gin-lsl** [comment]
good～
