### ISSUE TITLE
react 版本模块 初始化报错，无法新增节点

### ISSUE THREAD

**Issue by ttjimsen** [alibaba/butterfly#597]
## The current behavior

![image](https://user-images.githubusercontent.com/31235202/122632279-6638b980-d104-11eb-8988-25b54268083e.png)

## Your environment(such as: Butterfly version、Browser version、OS and so on)

`Butterfly version`:

`Browser version`:

`OS`:

**Comment by noonnightstorm** [comment]
@cctv1005s

**Comment by cctv1005s** [comment]
@ttjimsen 添加一个节点只是一个文本提示，我换一个提示好了，他只是告诉你，这之间能加入一个`Tooltip`

**Comment by cctv1005s** [comment]
ref: https://github.com/alibaba/butterfly/pull/599
