### ISSUE TITLE
锚点和线出现错位

### ISSUE THREAD

**Issue by ManbasJi** [alibaba/butterfly#600]
把组件放在el-tabs（element-ui）里面就会出现错位
![微信截图_20210621150446](https://user-images.githubusercontent.com/20039217/122724253-548f1780-d2a6-11eb-813f-6685587e449b.png)

**Comment by noonnightstorm** [comment]
这个问题因为界面没渲染完或者有切换动画没走完就开始渲染小蝴蝶，这时候需要延时渲染下

**Comment by ManbasJi** [comment]
> 这个问题因为界面没渲染完或者有切换动画没走完就开始渲染小蝴蝶，这时候需要延时渲染下

好的谢谢，解决了
