### ISSUE TITLE
可以打包成静态html和js代码吗

### ISSUE THREAD

**Issue by liuyang77886** [alibaba/butterfly#602]
## The current behavior

我想打包成静态代码放到nginx中
或者可以有其他方式，我去百度搜索也可以
## The expected behavior

我想打包成静态代码放到nginx中
或者可以有其他方式，我去百度搜索也可以
## Your environment(such as: Butterfly version、Browser version、OS and so on)

`Butterfly version`:

`Browser version`:

`OS`:

**Comment by noonnightstorm** [comment]
可以的哈～你npm下载下来的，dist里面的index.js的index.css，可以直接放到cdn上的哈～你通过script引入之后，我会在window对象上注入Butterfly
