### ISSUE TITLE
请问有无流程图实现参数传递的例子

### ISSUE THREAD

**Issue by wxrl** [alibaba/butterfly#608]
JS/NODE新人。需要实现一个在线数据处理的前端（传参到后台的流程图），由用户在UI通过拖拉各个sub module（block）进行数据处理。每个sub module（block）里面用户可以更改相应的参数。参数的项目和各项目默认数值已定（通过读取各sub module对应的conf json），用户load sub module之后可以在UI上改参数数值，确定后生成新的json给后台程序用。谢谢。

**Comment by noonnightstorm** [comment]
我大概了解你的流程了，你可以在节点上附带你各种需要的数据，然后你修改完，最后你通过canvas.getDataMap()的方式拿到全部数据，组装给后端即可。
