### ISSUE TITLE
关于数据存储

### ISSUE THREAD

**Issue by funs-scaler** [alibaba/butterfly#609]
请教一下this.canvas.getDataMap(),流程图返回的数据怎么发给服务器存储呢？数据中怎么会出现无限循环的引用呢？使用example/analysis获取数据
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'BaseNode'
    |     property 'endpoints' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'BaseEndpoint'
    |     property 'options' -> object with constructor 'Object'
    --- property '_node' closes the circle

![WeChatddf63b9e524db61e7f2411e258f7549b](https://user-images.githubusercontent.com/32733173/123763456-6439dc00-d8f6-11eb-9e91-e3a5c86d2131.png)

**Comment by noonnightstorm** [comment]
这个需要你自己处理下的哈
