### ISSUE TITLE
redraw 不起作用，接收不到回调，也没有报错

### ISSUE THREAD

**Issue by ManbasJi** [alibaba/butterfly#610]
![微信截图_20210630104832](https://user-images.githubusercontent.com/20039217/123894445-c1826b80-d990-11eb-9617-a74248fbf6ad.png)
在redraw 前数据已经更新，但是画布一直没有重新渲染，回调也收不到。不知道是bug还是我姿势不对

**Comment by ManbasJi** [comment]
node 内容过长的话，会导致布局出现重叠，数据是在new Canvas 之前就处理好的
![微信截图_20210630105516](https://user-images.githubusercontent.com/20039217/123895105-de6b6e80-d991-11eb-987e-cd1a35afc136.png)

**Comment by ManbasJi** [comment]
> ![微信截图_20210630104832](https://user-images.githubusercontent.com/20039217/123894445-c1826b80-d990-11eb-9617-a74248fbf6ad.png)
> 在redraw 前数据已经更新，但是画布一直没有重新渲染，回调也收不到。不知道是bug还是我姿势不对

我用的是treeCanvas，发现treeCanvas的redraw方法并不能传参，所以导致我即使数据更新了，但是canvas一直没有变化

**Comment by noonnightstorm** [comment]
好的，我先看看

**Comment by ManbasJi** [comment]
> node 内容过长的话，会导致布局出现重叠，数据是在new Canvas 之前就处理好的
> ![微信截图_20210630105516](https://user-images.githubusercontent.com/20039217/123895105-de6b6e80-d991-11eb-987e-cd1a35afc136.png)

这个是配置间距设置过小导致的 getHGap

**Comment by ManbasJi** [comment]
> > ![微信截图_20210630104832](https://user-images.githubusercontent.com/20039217/123894445-c1826b80-d990-11eb-9617-a74248fbf6ad.png)
> > 在redraw 前数据已经更新，但是画布一直没有重新渲染，回调也收不到。不知道是bug还是我姿势不对
> 
> 我用的是treeCanvas，发现treeCanvas的redraw方法并不能传参，所以导致我即使数据更新了，但是canvas一直没有变化

目前的解决方式是把所有node和edge删除掉，然后重新draw

**Comment by noonnightstorm** [comment]
> > > ![微信截图_20210630104832](https://user-images.githubusercontent.com/20039217/123894445-c1826b80-d990-11eb-9617-a74248fbf6ad.png)
> > > 在redraw 前数据已经更新，但是画布一直没有重新渲染，回调也收不到。不知道是bug还是我姿势不对
> > 
> > 
> > 我用的是treeCanvas，发现treeCanvas的redraw方法并不能传参，所以导致我即使数据更新了，但是canvas一直没有变化
> 
> 目前的解决方式是把所有node和edge删除掉，然后重新draw

的确现在普通图的redraw是会全部清除再重新添加；现在tree图，只是会更新坐标，不会增删节点。这个的确是历史设计的缺陷，没考虑周全，现在不少用户在用着这个api，也不太好修改，只能兼容下了。

**Comment by noonnightstorm** [comment]
> > node 内容过长的话，会导致布局出现重叠，数据是在new Canvas 之前就处理好的
> > ![微信截图_20210630105516](https://user-images.githubusercontent.com/20039217/123895105-de6b6e80-d991-11eb-987e-cd1a35afc136.png)
> 
> 这个是配置间距设置过小导致的 getHGap

是的，这个你设置一下即可
