### ISSUE TITLE
使用在ts的项目中报错 Could not find a declaration file for module

### ISSUE THREAD

**Issue by liurongqing** [alibaba/butterfly#624]
## The current behavior

运行的时候报错，提示里面的模块都找不到

![WechatIMG56](https://user-images.githubusercontent.com/26001948/126416314-d80606e7-c272-421f-b818-76905acf1842.jpeg)

## The expected behavior

正常运行

## Your environment(such as: Butterfly version、Browser version、OS and so on)

`Butterfly version`:
"version": "4.0.30",

`Browser version`:
版本 91.0.4472.114（正式版本） (x86_64)

`OS`:
MacOS

**Comment by noonnightstorm** [comment]
好的，收到，我们尽快解决下

**Comment by noonnightstorm** [comment]
麻烦提供下ts的配置，谢谢

**Comment by liurongqing** [comment]
解决了 :yum: 
我在 `tsconfig.json` 中添加了个忽略隐式any的检测就好了
```json
"noImplicitAny": false
```
