### ISSUE TITLE
Edge能够添加颜色属性

### ISSUE THREAD

**Issue by kekeq** [alibaba/butterfly#631]
## What problem does this feature solve?
Edge修改颜色太麻烦了需要拓展线的基类，如果直接有颜色的属性方便多了，另外如果常见的Edge形式，例如：虚线等，可以有一个属性来选择会大大简化开发。

**Comment by noonnightstorm** [comment]
这个可以通过设置css来设置，也比较简单。我们也会考虑添加这个属性
