### ISSUE TITLE
butterfly-vue-endpoint嵌套在UI组件库中会失效（不能连线）

### ISSUE THREAD

**Issue by xinnai** [alibaba/butterfly#632]
您好，我这边使用您的库感觉很好，现在有一个重要的问题，我想使用UI组件库比如ElementUI或者Vuetify搭建页面，并且让页面中某个元素默认支持连线，于是我使用了butterfly-vue-endpoint，发现这个butterfly-vue-endpoint在任何组件库中是不生效的，但是放在div这样的元素里是可以连线的，请问怎么解决这个问题？感谢！
**elementUI写法**
`<el-row>
      <butterfly-vue-endpoint id="1" >111</butterfly-vue-endpoint>
    </el-row>`
**vuetify写法**
`<v-card max-width="344">
    <butterfly-vue-endpoint id="2" className="endpoint-2">
      content
    </butterfly-vue-endpoint>
</v-card>`

以上代码均使连线功能失效

**Comment by Zt448143356** [comment]
好的。我后面测试下，修复这个bug。尽快给予你答复。

**Comment by Zt448143356** [comment]
好了，这个bug已经修复了在1.0.3版本。

**Comment by xinnai** [comment]
@Zt448143356 试了，好用，给你个大大的赞👍，希望咱vue版本尽快完善，感谢感谢🙂
