### ISSUE TITLE
Vue中的自动化布局问题

### ISSUE THREAD

**Issue by kekeq** [alibaba/butterfly#634]
使用Dagre Layout作为自动布局，生效了，但是层级识别有问题。
顺带测试了下改为gridLayout,没有问题。

## The current behavior

![dcd798697e9c316ef53159ff5c8c0a3](https://user-images.githubusercontent.com/18187540/128135671-24fb7b11-cb75-48d1-8953-c2e887bc4ad6.png)

## The expected behavior

![ccf54427e1ad382e58e9b53f02000ac](https://user-images.githubusercontent.com/18187540/128135701-324a6954-e5ba-4cb3-aefb-b3c47872726b.png)

## Your environment(such as: Butterfly version、Browser version、OS and so on)
`Butterfly version`: Chrome

`OS`:windows10

## Steps To Reproduce, Maybe you can provide a simple demo.

`        layout: {`
`          type: 'dagreLayout',`
`          options: {`
`            rankdir: 'TB',`
`            nodesep: 50,`
`            ranksep: 50,`
`            controlPoints: false,`
`          },`
`        }`

**Comment by Zt448143356** [comment]
经过复现是存在这个问题，基本已经定位了。后面修复后再回复你

**Comment by Zt448143356** [comment]
在版本1.0.4已经修复

**Comment by Zt448143356** [comment]
已经修复，记得关下issues
