### ISSUE TITLE
是否和MFSU、TS兼容

### ISSUE THREAD

**Issue by GuanJdoJ** [alibaba/butterfly#638]
## What problem does this feature solve?
请问两个兼容问题
1、是否兼容umi的MFSU
2、是否支持TS
如果目前不兼容，后续有计划吗？

**Comment by noonnightstorm** [comment]
现在是支持ts的。umi的MFSU还没测试过。我们也正在把源码往ts上迁移。

**Comment by GuanJdoJ** [comment]
> 现在是支持ts的。umi的MFSU还没测试过。我们也正在把源码往ts上迁移。

好的，期待
