### ISSUE TITLE
plugins-pannel无法使用

### ISSUE THREAD

**Issue by zihjiang** [alibaba/butterfly#642]
环境: 
{
    "@ant-design/icons": "^4.5.0",
    "@ant-design/pro-descriptions": "^1.6.8",
    "@ant-design/pro-form": "^1.18.3",
    "@ant-design/pro-layout": "^6.15.3",
    "@ant-design/pro-table": "^2.30.8",
    "@antv/data-set": "^0.11.8",
    "@umijs/route-utils": "^1.0.36",
    "antd": "^4.14.0",
    "bizcharts": "^3.5.9",
    "bizcharts-plugin-slider": "^2.1.1",
    "butterfly-dag": "^4.0.37",
    "classnames": "^2.2.6",
    "gg-editor": "^2.0.4",
    "lodash": "^4.17.11",
    "moment": "^2.25.3",
    "numeral": "^2.0.6",
    "omit.js": "^2.0.2",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.1.1",
    "react-dom": "^17.0.0",
    "react-fittext": "^1.0.0",
    "react-helmet-async": "^1.0.4",
    "umi": "^3.5.0",
    "umi-serve": "^1.9.10"
  },
"devDependencies": {
    "@ant-design/pro-cli": "^2.0.2",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.2",
    "@types/jest": "^26.0.0",
    "@types/lodash": "^4.14.144",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-helmet": "^6.1.0",
    "@umijs/fabric": "^2.6.2",
    "@umijs/openapi": "^1.1.14",
    "@umijs/plugin-blocks": "^2.0.5",
    "@umijs/plugin-esbuild": "^1.0.1",
    "@umijs/plugin-openapi": "^1.2.0",
    "@umijs/preset-ant-design-pro": "^1.2.0",
    "@umijs/preset-dumi": "^1.1.7",
    "@umijs/preset-react": "^1.8.17",
    "@umijs/preset-ui": "^2.2.9",
    "@umijs/yorkie": "^2.0.3",
    "carlo": "^0.9.46",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.1.1",
    "detect-installer": "^1.0.1",
    "enzyme": "^3.11.0",
    "eslint": "^7.1.0",
    "express": "^4.17.1",
    "gh-pages": "^3.0.0",
    "jsdom-global": "^3.0.2",
    "lint-staged": "^10.0.0",
    "mockjs": "^1.0.1-beta3",
    "prettier": "^2.3.2",
    "puppeteer-core": "^8.0.0",
    "stylelint": "^13.0.0",
    "typescript": "^4.2.2"
  }
使用方式:
![image](https://user-images.githubusercontent.com/21021327/129450012-1a392fce-e7cd-47d1-8bdd-15e09e253e82.png)
报错:
![image](https://user-images.githubusercontent.com/21021327/129450027-8d44fc94-0210-4ac6-801d-49c7ef824496.png)

**Comment by zihjiang** [comment]
改成这样就可以了, 不过好像都是些测试数据, 根据文档改也没效果, 请问有例子么
import * as panelPlugins from 'butterfly-dag/plugins/panel/dist/index.js';

**Comment by noonnightstorm** [comment]
@cctv1005s 貌似咱们文档有误，有空修改下

**Comment by zihjiang** [comment]
奇怪的是, 我明明是这样配置的
![image](https://user-images.githubusercontent.com/21021327/129558383-c393b943-07ef-4e3f-a42a-5ed2a10c3cfd.png)
结果竟然是
![image](https://user-images.githubusercontent.com/21021327/129558453-df66469d-e82a-492c-a461-656b46f0977c.png)

**Comment by noonnightstorm** [comment]
@Zt448143356 帮忙看看

**Comment by Zt448143356** [comment]
你的那个图应该是加载了的。但是被顶到最下面了，视口外面了所以没看到。
这里的type的意思是使用默认的basic的内置图。
你如果不想要用内置的部分。type 不写就可以了。当前内置了‘basic和'uml'两个type。写了其他type：会有如下提示：
![image](https://user-images.githubusercontent.com/48010552/129774650-3deeb736-458f-4286-ae57-395a146816d1.png)
![image](https://user-images.githubusercontent.com/48010552/129773561-0dd5f9a2-1e9a-4312-a586-8c98a243a86b.png)
再给你提供一个demo地址（测试demo）: https://github.com/alibaba/butterfly/tree/master/plugins/panel/example
导入方式部分可能是plugins部分还没开始统筹规划，所以这样导入还有问题。

**Comment by zihjiang** [comment]
果然可以了, 原来这个type是内置的测试数据... 谢了

**Comment by Zt448143356** [comment]
哈哈哈。不算内置的测试数据。是给其他开发者提供的内置数据。有些模块可能会用到basic啊uml啊这样的一些基础图片，所以就内置了。也支持拓展。
