### ISSUE TITLE
【help】有个距离的问题请教下

### ISSUE THREAD

**Issue by kailong321200875** [alibaba/butterfly#645]
当我画布有偏移和缩放的时候，我要拖拽一个元素在画布上，然后在动态添加node，可是这时候的top和left要怎么计算。。当没有缩放的情况下，位置是准确的，不管有没有偏移。

**Comment by noonnightstorm** [comment]
请看画布上：terminal2canvas和canvas2terminal的两个方法，调用后我都会帮你转换坐标

**Comment by kailong321200875** [comment]
> 请看画布上：terminal2canvas和canvas2terminal的两个方法，调用后我都会帮你转换坐标

好的，可以了，位置都准确的计算出来了，谢谢。
