### ISSUE TITLE
有没有VUE版的数据/字段映射组件

### ISSUE THREAD

**Issue by kailong321200875** [alibaba/butterfly#646]
感觉这个插件对于vue的支持不太友好，有很东西都没办法定制化的样子。所以想问问，用vue能否实现react版的数据/字段映射，具体思路是什么样子的。

**Comment by noonnightstorm** [comment]
好像有的，之前有一个贡献者写过一个，但里面逻辑是用原生写的，就用vue包裹了一层，可以问问 @Zt448143356

**Comment by kailong321200875** [comment]
因为这个功能比较紧急，感觉这个插件对于vue的支持不太优化，很多东西都不能像react那样定制化，所以就想问问看，有没有vue版的这个组件。。

**Comment by Zt448143356** [comment]
不确定是否存在这样的组件，我要去联系那个开发者团队。他们是否愿意开源也未知。最稳妥的方案是，自己基于dag去写一套vue的数据/字段映射组件。用原生然后套一层Vue。不推荐在butterfly-vue的版本上实现，因为，butterfly-vue还存在好一些bug。还没来得急去修复。
具体的实现思路可以去看react版的数据/字段映射组件。实现思路大体上是一致的。
