### ISSUE TITLE
为什么拖出来的node一定是PanelNode

### ISSUE THREAD

**Issue by zihjiang** [alibaba/butterfly#649]
如题, 我阅读源码后发现, 为什么拖出来的node一定是PanelNode, 我自定义class不行么
![image](https://user-images.githubusercontent.com/21021327/129907570-7bfd32bc-cdc1-4fd9-8cba-d0483d6579ea.png)
![image](https://user-images.githubusercontent.com/21021327/129907593-4a4e3393-62df-43f2-a40c-24aef6f2b6a4.png)
![image](https://user-images.githubusercontent.com/21021327/129907610-b1ce73cc-8716-45d1-982c-af8d71470435.png)
ref: https://github.com/alibaba/butterfly/blob/master/plugins/panel/src/index.js

**Comment by noonnightstorm** [comment]
这个是定制性的插件，只能是PanelNode

**Comment by zihjiang** [comment]
了解,
