### ISSUE TITLE
butterfly-vue(react) process.js在处理edge, type应该是可被覆盖的

### ISSUE THREAD

**Issue by yolofit** [alibaba/butterfly#652]
## The current behavior

radial layout， addEdges会报错，如下图.
```
const edge = {
  source: '1',
  target: '2',
  type: 'node'
}
```

![image](https://user-images.githubusercontent.com/20294811/130352361-221006e8-1a0c-4e27-a405-84eea1e7b964.png)

## The expected behavior

concentricLayout、forceLayout、fruchterman、radial等layout的edge，type并非endpoint

process.js不应该写死"type: endpoint" ， 否则new EdgeClass的type都是有问题的

![image](https://user-images.githubusercontent.com/20294811/130352277-64747f8f-a6e8-4aca-8ad5-ce3c0034cb4b.png)

## Your environment(such as: Butterfly version、Browser version、OS and so on)

`Butterfly version`:

`Browser version`:

`OS`:

**Comment by Zt448143356** [comment]
已经修复，记得关下issues
