### ISSUE TITLE
npm install 失败

### ISSUE THREAD

**Issue by TheMrCoder** [alibaba/butterfly#661]
## Your environment(such as: Butterfly version、Browser version、OS and so on)

`Butterfly version`:
最新
`Browser version`:
无
`OS`:
mac
## Steps To Reproduce, Maybe you can provide a simple demo.
 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: butterfly-dag@4.1.3
npm ERR! Found: rollup@2.56.3
npm ERR! node_modules/rollup
npm ERR!   dev rollup@"~2.56.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer rollup@"^1.4.1" from rollup-plugin-extensions@0.1.0
npm ERR! node_modules/rollup-plugin-extensions
npm ERR!   dev rollup-plugin-extensions@"~0.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/10018450/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/10018450/.npm/_logs/2021-08-27T02_48_57_588Z-debug.log

**Comment by qq254963746** [comment]
> 已解决，使用如下方式 If you're getting this error on Mac OSX ensure to run $ brew install cairo and $ brew install pango

我跟你一样的错误，安装了这两个东西还是没有解决
