### ISSUE TITLE
请问vue版的node是否有暴露出hover事件？

### ISSUE THREAD

**Issue by leeJie1994** [alibaba/butterfly#663]
使用场景里需要用到监听鼠标是否悬停在node节点上，请问vue版的node节点是否有暴露出hover事件？或者有什么方式能监听node节点的hover触发？

**Comment by Zt448143356** [comment]
node节点支持自定义呀，你直接在自己的node节点里自己监听hove事件就可以呀。

**Comment by Zt448143356** [comment]
若你需要外部处理一些事件，你可以在node节点emit方法传出。在外部处理。
demo地址如下：https://github.com/alibaba/butterfly/tree/master/vue/example/src/page/treeDemo
你可以整个下载下去跑一下

**Comment by leeJie1994** [comment]
好的，谢谢
