### ISSUE TITLE
官网上的实例只有图片，没找到例子

### ISSUE THREAD

**Issue by qianzhangsheng** [alibaba/butterfly#665]
![image](https://user-images.githubusercontent.com/1262247/131305739-e3c106c8-2043-4eea-825d-545f441e2ffe.png)
没有找到这个例子😭

**Comment by noonnightstorm** [comment]
非常抱歉，这个是咱们公司内部的场景，无法对外提供代码。这个只能自己去编写

**Comment by qianzhangsheng** [comment]
> 非常抱歉，这个是咱们公司内部的场景，无法对外提供代码。这个只能自己去编写

谢谢啦，我自己实现看看😊
