### ISSUE TITLE
vue可以使用node里的拓展类Class吗？

### ISSUE THREAD

**Issue by qianzhangsheng** [alibaba/butterfly#668]
https://github.com/alibaba/butterfly/blob/master/docs/zh-CN/node.md#class-class----%E9%80%89%E5%A1%AB
vue在 `nodes` 数据里添加了 `Class` 拓展类好像没用😭

**Comment by Zt448143356** [comment]
是的啊。兄弟，这是后续准备要支持的。当前支持以下两种方式。
文档：https://github.com/alibaba/butterfly/blob/master/docs/zh-CN/vue.md
![image](https://user-images.githubusercontent.com/48010552/131500095-320b1c02-0c38-4292-8611-7f82499036c3.png)
最近没时间升级vue版本。比较忙。vue版本还有好几个bug没有修复。
可以支持下，加入我们一起开发butterfly。

**Comment by qianzhangsheng** [comment]
> 是的啊。兄弟，这是后续准备要支持的。当前支持以下两种方式。
> 文档：https://github.com/alibaba/butterfly/blob/master/docs/zh-CN/vue.md
> demo：https://github.com/alibaba/butterfly/tree/master/vue/example
> ![image](https://user-images.githubusercontent.com/48010552/131500095-320b1c02-0c38-4292-8611-7f82499036c3.png)
> 最近没时间升级vue版本。比较忙。vue版本还有好几个bug没有修复。
> 可以支持下，加入我们一起开发butterfly。

👌好的，目前在写流程编辑器，写完demo我可以上传
