### ISSUE TITLE
是否能开源或者分享更多案例

### ISSUE THREAD

**Issue by pq-dong** [alibaba/butterfly#671]
## What problem does this feature solve?

您好，浏览了你们的API和DEMO，butterfly很强大，希望增加更多案例。例如可以开源或者分享readme中
![image](https://user-images.githubusercontent.com/40668796/131670396-20df3cc3-3ad7-4d95-a9b4-0bf8b9fe770d.png)
z这个流程图的源码吗？

**Comment by noonnightstorm** [comment]
嗯嗯，这个实在没办法开源，这个是咱们内部的业务，仅供参考，十分抱歉

**Comment by javacoderxxp** [comment]
> ![image](https://user-images.githubusercontent.com/1262247/131777495-3f06f0c5-7dfd-4181-9dbf-fcf5d0348018.png)
> 用vue写了一个

你好,请问你这边的vue代码可以共享吗, 我想学习参考一下!感谢!
