### ISSUE TITLE
vue版本，drag以后node再随意拖动，连线以后node会恢复到drag时候的位置，这个需要怎么解决，发现demo也有这个问题

### ISSUE THREAD

**Issue by qianzhangsheng** [alibaba/butterfly#672]
vue版本，drag以后node再随意拖动，连线以后node会恢复到drag时候的位置，这个需要怎么解决，发现demo也有这个问题

![Tab-1630554837405](https://user-images.githubusercontent.com/1262247/131779431-8a090188-0ce8-4046-b51d-95d4c42ef1fb.gif)

**Comment by qianzhangsheng** [comment]
> 添加连线和添加节点的时候同步一下初始值，因为拖动会触发更新，更新会拿初始值

好的

**Comment by Zt448143356** [comment]
有个新人提了这个问题。我看了下，是一个小layout的bug。没有设置layout的我也去layout了（前面一位其他开发者提供pr的时候没有检查到这个地方导致的）。我将在1.0.7版本修复这个问题。
