### ISSUE TITLE
内置左侧面板(panelPlugins)上的图形拖拽到canvas上宽度问题

### ISSUE THREAD

**Issue by cuidong626** [alibaba/butterfly#673]
比如：内置左侧面板(panelPlugins)上的图形的宽高分别是200，100.拖拽到canvas画布上就变成正方形。

![image](https://user-images.githubusercontent.com/22650893/131955410-89a110c2-c805-4b0d-a9d6-4e052842468f.png)
![image](https://user-images.githubusercontent.com/22650893/131955428-d491a726-aea0-4a9d-9ede-9656bc119261.png)

看了下源码，addNode的时候没有左侧面板(panelPlugins)上节点的宽高传过去。PanelNode里面没有宽高默认就是36

**Comment by Zt448143356** [comment]
对啊。所以你要自己设置你拖拽节点的宽高啊，兄弟

**Comment by Zt448143356** [comment]
我重新看了下，是的。是一个bug。我修一下。
