### ISSUE TITLE
请问edgeLabel怎么抛出事件给外部处理

### ISSUE THREAD

**Issue by kuxuee** [alibaba/butterfly#674]
vue emergency demo中在base-label中调用this.$emit("dblclick"）  但是外层butterfly-vue组件监听不到这个事件

**Comment by noonnightstorm** [comment]
@Zt448143356

**Comment by Zt448143356** [comment]
查看了下代码。是的，没有支持这个部分，现在就支持了node的。等等我支持下，晚上给你发个版本。

**Comment by kuxuee** [comment]
感谢！^_^

**Comment by Zt448143356** [comment]
发布了1.0.6，你试试

**Comment by kuxuee** [comment]
可用，点赞！
