### ISSUE TITLE
Vue edge的属性丢失

### ISSUE THREAD

**Issue by kekeq** [alibaba/butterfly#675]
## The current behavior

edge的属性丢失，导致线的颜色无法显示

## The expected behavior

在edge.js中可以获取完整的属性，包括自定义属性。

## Steps To Reproduce, Maybe you can provide a simple demo.
 
mockData：
  edges: [
    {
      id: '1.bf_endpoint_1-2.bf_endpoint_1',
      sourceNode: '1',
      targetNode: '2',
      source: 'bf_endpoint_1',
      target: 'bf_endpoint_1',
      color: 'red',
    }
]

运行时观察process.js（24行）中，map后的edge
    edges: edges.map(edge=> {
      consolo.log(edge);
      return {
        type: 'endpoint',
        ...edge,
        Class: Edge,
      };
    }),

此时的edge已经缺少color属性，将edge改为item后color属性恢复。

    edges: edges.map(item=> {
      consolo.log(item);
      return {
        type: 'endpoint',
        ...item,
        Class: Edge,
      };
    }),

**Comment by Zt448143356** [comment]
兄弟，vue版本还不支持class的渲染。你想要做啥啊。你提出的这个我复现了一下，是正常的。
![image](https://user-images.githubusercontent.com/48010552/132303434-4dc50637-74d4-4649-a380-e90679f3a855.png)
![image](https://user-images.githubusercontent.com/48010552/132303461-c1b714b3-b360-4af2-9c4f-059b43c292b2.png)

**Comment by kekeq** [comment]
准备做一个编排图，随着脚本的执行，连接线，会有样式的变更，例如虚线，实线，颜色也对应变更。

**Comment by Zt448143356** [comment]
这个需要edge的定制支持。但是vue还不支持edge的class定制（暂时还没有时间支持）。你的这个想法可以使用dag（原生）封装一个vue的编排图组件。仅提供建议。dag没有vue的demo。都是react的demo。流程图我记得react有一份，是否开源了不确定。你可以看下首页的readme里有没有。你会react的话，就可以参考demo写一份vue的组件。

**Comment by kekeq** [comment]
OK,我来尝试添加这个部分功能
