### ISSUE TITLE
啥时候支持vue3??

### ISSUE THREAD

**Issue by dongson001** [alibaba/butterfly#676]
## What problem does this feature solve?
啥时候支持vue3??

**Comment by Zt448143356** [comment]
vue2都还没有完全支持。。vue3估计还早。兄弟，你可以加入我们支持下。发布个butterfly-vue3？
以前我记得有一个dragonfly-dag。你可以看看可以用不
https://github.com/lchrennew/dragonfly-dag

**Comment by dongson001** [comment]
能力有限啊，虽然想贡献

**Comment by Zt448143356** [comment]
可以试试的。大家都从0开始。你可以看看dragonfly-dag这个，他是vue3的我记得，当时开发vue2的时候这位开发者也在同步开发vue3.最近好像没有怎么维护了。你可以去看看。使用下，不能肯定好用哈。记得关下issues。感谢

**Comment by dongson001** [comment]
好的。谢谢
