### ISSUE TITLE
butterfly-vue 1.0.6版本通过鼠标连接两个endpoint构建edge时，node的位置自动发生了变化

### ISSUE THREAD

**Issue by kuxuee** [alibaba/butterfly#677]
## The current behavior

butterfly-vue 1.0.6版本，两个node拖动改变位置，然后通过鼠标连接两个endpoint构建edge时，node的位置自动发生了变化，自动改变到拖动前的位置。

## The expected behavior

node的位置应保持在拖动后的坐标不变。

## Your environment(such as: Butterfly version、Browser version、OS and so on)

`Butterfly version`:
1.0.6

`Browser version`:
Microsoft Edge
版本 93.0.961.38 (官方内部版本) (64 位)

`OS`:
win10

**Comment by Zt448143356** [comment]
https://github.com/alibaba/butterfly/issues/672#issue-986079901

**Comment by Zt448143356** [comment]
兄弟你可以看看这个issues。和你一样的问题

**Comment by kuxuee** [comment]
请问怎么更新初始值，初始值是通过:canvasData属性绑定进去的，我看添加连线时，在logCreateEdge打印组件的canvasData，即this.$refs.butterfly.canvasData坐标已经是最新值了。难道是要更新组件里的canvas.nodes属性吗

**Comment by Zt448143356** [comment]
我看了下，是一个小layout的bug。没有设置layout的我也去layout了（前面一位其他开发者提供pr的时候没有检查到这个地方导致的）。我将在1.0.7版本修复这个问题。
他们的解决方案我也没看懂。。。。你升级下1.0.7就修复了这个bug。

**Comment by kuxuee** [comment]
已解决，赞。
