### ISSUE TITLE
canvasData.render渲染报错

### ISSUE THREAD

**Issue by magicalxiaochen** [alibaba/butterfly#679]
## The current behavior
canvasData.render渲染，采用object类型（.vue)文件的方式，
vue文件使用 ts注册, 如下所示
```vue
<template>
  <div class="node">{{ itemData.label }}</div>
</template>

<script lang="ts">
import { Vue, Component, Prop } from 'vue-property-decorator';

@Component
export default class CustomNode extends Vue {
  @Prop({ default: {} }) private itemData!: object;

  created() {
    console.log(this.itemData);
  }
}
</script>
```

`render: CustomNode` 时报错提示：`[Vue warn]: Error in mounted hook: "Error: node存在render属性，应该为string或者object类型，现在是function"`

**Comment by noonnightstorm** [comment]
@Zt448143356

**Comment by Zt448143356** [comment]
还没用ts试过。我有空了就试试，或者你给我提供下错误demo。

**Comment by Zt448143356** [comment]
这种类似的class的写法，.vue文件就是function的形式。这种形式，还没支持。后续支持的class写法的（function）的也不支持这样来写。。
![image](https://user-images.githubusercontent.com/48010552/132608524-b4f28bfa-0fd0-47ae-b703-54125d20a723.png)
你可以试试这样来写。vue文件。用ts就好了。不要继承Vue。。
你这个的写发和react一样。。。感觉是react转vue的用户。。

**Comment by magicalxiaochen** [comment]
好的 感谢
