### ISSUE TITLE
在vue例子中，拖拽示例的问题 

### ISSUE THREAD

**Issue by kailong321200875** [alibaba/butterfly#684]
当拖拽到一个默认位置后如：100， 100，然后拖动当前这个节点到其他位置：200，200。然后进行连线，会发现这个节点又重新回到100，100中。
或者，在重新拖出一个节点过来，其他的节点都会全部回到初始位置

**Comment by Zt448143356** [comment]
https://github.com/alibaba/butterfly/issues/677#issue-989731440
看这个issue

**Comment by Zt448143356** [comment]
重新拉下代码吧。我记得我修过这个bug了。你的可能是老版本的代码，你看vue的版本到1.0.7基本就是最新的vue的代码

**Comment by kailong321200875** [comment]
> 重新拉下代码吧。我记得我修过这个bug了。你的可能是老版本的代码，你看vue的版本到1.0.7基本就是最新的vue的代码

可以了，谢谢
