### ISSUE TITLE
Vue控件的zoomGap属性无效，无法控制滚轮的缩放步进

### ISSUE THREAD

**Issue by kekeq** [alibaba/butterfly#688]
Vue控件的zoomGap属性无效，无法控制滚轮的缩放步进

canvasConfig: {
        linkable: false, // enable connect edges
        draggable: false, // enable drag nodes
        zoomable: true, // enable zoom canvas
        autoResizeRootSize: true, // automatically adapt to the root size, the default is true
        moveable: true, // enable move canvas
        zoomGap: 0.01, // 鼠标放大缩小间隙设置
        autoFixCanvas: { // 节点拖动或连线拖动到画布边缘时，画布自动延展
          enable: true,
          autoMovePadding: [20, 20, 20, 20] // 触发自动延展的画布内边距
        },
        layout: {
          type: 'dagreLayout',
          options: {
            rankdir: 'LR',
            nodesep: 25,
            ranksep: 25,
            controlPoints: false
          }
        },
        theme: {
          edge: {
            type: 'Bezier', 
            label: '', 
            arrow: false
          }
        }
      }

**Comment by Zt448143356** [comment]
兄弟你配错了吧。。不是在这个层级配置。我记得是在theme中配置的这个。
详细可查
https://github.com/alibaba/butterfly/blob/master/docs/zh-CN/canvas.md

**Comment by kekeq** [comment]
哦哦，不过缩放的实际步进为(zoomGap * 125)

**Comment by Zt448143356** [comment]
![image](https://user-images.githubusercontent.com/48010552/133539249-50ae104d-5a57-4e5d-a1b5-b00b895f7e59.png)
感觉有问题的话，你可以看看源码。
