### ISSUE TITLE
Vue arrow箭头方向反了

### ISSUE THREAD

**Issue by kekeq** [alibaba/butterfly#690]
![image](https://user-images.githubusercontent.com/18187540/133540322-a1377650-2202-4167-a755-611d736471f3.png)

**Comment by Zt448143356** [comment]
明白了。最近太忙了。后面修复了再回复你。

**Comment by Zt448143356** [comment]
兄弟，我感觉你的复现情况可能和我的不一样。可以提供下你的复现demo吗？或者告诉我你的是怎么复现的。给我复现数据也可以

**Comment by Zt448143356** [comment]
兄弟试试butterfly-vue@1.0.8这个版本。我修复了自定义模式下的线的箭头反的问题。

**Comment by kekeq** [comment]
> 兄弟试试butterfly-vue@1.0.8这个版本。我修复了自定义模式下的线的箭头反的问题。

OK,今天有时间我确认一下，因为原版本不支持class自定义，我还魔改了点东西，得merge你的代码

**Comment by Zt448143356** [comment]
ok，好的。前面是自定义锚点才会有这个bug。其他的是没有问题的

**Comment by Zt448143356** [comment]
emmm，兄弟你那里修复了吗？修复了的话，可以close下吗？感谢。
