### ISSUE TITLE
框选模式不起作用

### ISSUE THREAD

**Issue by daviehuang** [alibaba/butterfly#725]
我利用系统提供的vue sample做了细微调整，想试一下框选模式，具体代码改动如下：
改动文件：butterfly/vue/example/src/page/drag.vue
改动代码，在finishLoaded(VueCom)方法内新增了一行：this.canvansRef.setSelectMode(true, ['node'], 'include');

```
    finishLoaded(VueCom) {
      this.butterflyVue = VueCom;
      this.canvansRef = VueCom.canvas;
      window.butterflyVue = VueCom;
      this.canvansRef.setSelectMode(true, ['node'], 'include');
    },
```

运行结果：无法框选node节点。

butterfly-dag版本：master
OS: macOS Big Sur v11.5.2

**Comment by Zt448143356** [comment]
兄弟是有效的。
![butterfly-vue](https://user-images.githubusercontent.com/48010552/135240261-48ed3d3f-6dd1-41dd-8ad6-a920877df457.gif)
![butterfly-vue](https://user-images.githubusercontent.com/48010552/135238951-29dc416b-e177-4a46-b7c4-29806477c914.gif)

**Comment by daviehuang** [comment]
首先感谢🙏，反馈挺及时。
有点小郁闷，看样子代码没问题，是我的环境出问题了

**Comment by Zt448143356** [comment]
你可以尝试重新拉下代码。以及重新安装依赖。

**Comment by ZhangYukuan** [comment]
> 首先感谢🙏，反馈挺及时。 有点小郁闷，看样子代码没问题，是我的环境出问题了

我也遇到了这个问题，打开框选模式，node就无法拖动，请问你是怎么解决的？

butterfly-dag版本：v4.3
butterfly-vue版本：v1.0.20
OS: macOS Sonoma v14.4.1

**Comment by daviehuang** [comment]
这个问题有人碰到，有人没碰到，可能跟环境（或浏览器）有关系。
时间太久，我当初做的代码找不到了。可以debug一下，应该是鼠标按下时event.target出问题了，我改动了组件内的某行代码。

*Regards,*

*Davie Huang*

*___________________________________________________________*

*CE PRODUCT TEAM LEADER* | *China Systems Co., Ltd.*

*5th Floor, Building No.3, No.699-8 Xuan Wu Avenue*

*Xuan Wu District, Nanjing, P.R.C.  210042*

*___________________________________________________________*

*Tel: **+86 25 8558 2112 ext: <%2B86%2025%208558%202112%20ext%3A336>303*

*Skype: cscdavie*


Senlin ***@***.***> 于2024年10月29日周二 12:20写道：

**Comment by ZhangYukuan** [comment]
十分感谢！
但感觉咱俩遇到的好像不是同一个问题。
我可以详细描述下我的问题：
1、打开框选模式
     this.canvansRef.setSelectMode(true)
2、开启事件监听
     this.canvansRef.on('system.multiple.select', (data) => {
        console.log(data);
        这里拿到的数据是对的
      });
3、当做完前两步的操纵后，无论我拖拽node、group或是画布上其他可拖拽的项目，都会触发框选操作。
我目前正在阅读源码，若能解决我将在此反馈或发起pr。如若你有更好的方案也请不吝赐教。
再次感谢！

**Comment by Zt448143356** [comment]
> 十分感谢！ 但感觉咱俩遇到的好像不是同一个问题。 我可以详细描述下我的问题： 1、打开框选模式 this.canvansRef.setSelectMode(true) 2、开启事件监听 this.canvansRef.on('system.multiple.select', (data) => { console.log(data); 这里拿到的数据是对的 }); 3、当做完前两步的操纵后，无论我拖拽node、group或是画布上其他可拖拽的项目，都会触发框选操作。 我目前正在阅读源码，若能解决我将在此反馈或发起pr。如若你有更好的方案也请不吝赐教。 再次感谢！

兄弟，你看下这个文档，框选模式和普通拖动画布模式是互斥的。
这个能否解答你的疑惑。
https://github.com/alibaba/butterfly/blob/master/docs/zh-CN/canvas.md#canvassetselectmode-boolean-contents--selectmode
![image](https://github.com/user-attachments/assets/8004b325-941d-4154-a6ce-cdb649f0c53c)

**Comment by ZhangYukuan** [comment]
这个互斥说的应该是和画布的整体拖拽互斥（moveable属性）。如果和所有的拖拽都互斥那楼上[Zt448143356](https://github.com/Zt448143356)所实现的这个效果就没这么简单了。

**Comment by Zt448143356** [comment]
emmm.之前那个效果就是我实现的。我是vue2组件的作者。

我查了下，是dag的bug。我回退到4.2.12版本是ok的。
估计是最新的版本有bug，需要修复一下。
你先用4.2.12试一下，或者你测一下那个版本引入的这个bug。我到时候看下源码处理一下。

**Comment by ZhangYukuan** [comment]
在此，先表达敬意和感谢！

然后再反馈下我的问题：
首先，4.1.12版本确实可以实现批量框选拖拽，但好像只有第一次会生效，之后便无法再框选（我看了这部分源码，感觉dag最初的设计应该是开启框选模式后，只要在空白处拖拽都应该触发框选操作）。
然后就是我在4.3.28版本上测试发现框选模式打开后node的mousedown事件好像没有触发。其他版本我还没试，我今天下午应该会进一步研究下源码。若有进展会及时反馈。

十分感谢开源作者的贡献！

**Comment by Zt448143356** [comment]
估计是要看下查一下了问题了。
dag应该慢慢不维护了。

后续新的这类dag图组件库的选型建议使用vue-flow、react-flow、x6、G6等更好的开源仓库吧。叹气。

**Comment by ZhangYukuan** [comment]
> 估计是要看下查一下了问题了。 dag应该慢慢不维护了。
> 
> 后续新的这类dag图组件库的选型建议使用vue-flow、react-flow、x6、G6等更好的开源仓库吧。叹气。


其实我也对比了这几个组件库，目前选型更倾向于X6。只是先demo了butterfly-dag，发现了这个bug，放不下而已！
听君一席话，我更坚定的感觉到butterfly应该是已经完成了它的历史使命！
我已放下心结。

感谢，祝好！
