### ISSUE TITLE
请问vue版本支持setGuideLine吗？

### ISSUE THREAD

**Issue by leeJie1994** [alibaba/butterfly#728]
vue版本支持setGuideLine功能么？或者有其他设置辅助线的属性么？

**Comment by leeJie1994** [comment]
取消辅助线的时候设置显示参数位false，会报错
![image](https://user-images.githubusercontent.com/30051774/137117232-842fc9aa-8299-414e-8539-1a9aa2d2469f.png)
请问这是已知bug，还是我这边的设置的问题？
![image](https://user-images.githubusercontent.com/30051774/137117396-c6597c45-dabf-4d97-96c3-43087b6e6086.png)

**Comment by Zt448143356** [comment]
emmmmm。这确实是一个bug。。我们修复下。修复完毕后告诉你
