### ISSUE TITLE
node能否通过鼠标拖动来改变大小？

### ISSUE THREAD

**Issue by daviehuang** [alibaba/butterfly#731]
如题

我现在在使用vue做原型，在某些场景下需要通过鼠标来改变node的大小，请问是否已经具备了这样的功能？如果有，也没有示例代码可以参考？

非常感谢

**Comment by noonnightstorm** [comment]
可以的，但需要自己实现，可以参考group的源码，看看set

**Comment by daviehuang** [comment]
我知道怎么用代码改变node的大小，但是不清楚如何才能捕获到像node:resize这样的事件

**Comment by noonnightstorm** [comment]
你要自己写一个dom来监听mousedown和mousemove事件，后然自己操作dom来改变其width和height
