### ISSUE TITLE
Edges overlap when connecting between nodes 

### ISSUE THREAD

**Issue by maisnamraju** [alibaba/butterfly#762]
## The current behavior
When connecting nodes, is there a way to make sure that the path doesn't overlap on top of an existing node ?
![Screenshot 2022-01-07 at 1 52 54 PM](https://user-images.githubusercontent.com/2786378/148504158-dc0c7002-713b-4ca3-befc-961b04264c24.png)

## The expected behavior
I would to connect nodes without overallping the edges between nodes. 
## Your environment(such as: Butterfly version、Browser version、OS and so on)
Currently I am on 
"butterfly-dag": "^4.1.22",
"butterfly-vue": "^1.0.10",

**Comment by Zt448143356** [comment]
l got it.
I will provide you with a solution in the next Comment

**Comment by Zt448143356** [comment]
"butterfly-dag": "^4.1.22" =>  "^4.1.23",
like this 
``` js
// canvasConfig
canvasConfig:{
        disLinkable: true,
        linkable: true,
        draggable: true,
        zoomable: true,
        moveable: true, 
        theme: {
          edge: {
            shapeType: 'Flow',
            dragEdgeZindex: 400  // this，You can set the Z-index of the edge
          }
        }
      },
```
You can try setting it to 400

**Comment by Zt448143356** [comment]
Thank you for your feedback！

**Comment by maisnamraju** [comment]
Awesome and thanks. Also might I ask the reason butterfly uses jquery ?

**Comment by Zt448143356** [comment]
This is a historical reason(jquery was very popular when coding butterfly). jquery was first used to facilitate DOM operation.
We have an idea to remove jQuery.But the workload is very heavy.
