### ISSUE TITLE
umi+ts+react项目中使用butterfly-react会报错找不到模块

### ISSUE THREAD

**Issue by xiayukun** [alibaba/butterfly#781]
![微信截图_20220215200234](https://user-images.githubusercontent.com/14273571/154058522-15d30be0-78f7-4d57-8671-546efa762df2.png)
我在types目录下已经declare了此模块，引用和运行都没有报错
![image](https://user-images.githubusercontent.com/14273571/154058687-dbd79162-53f0-4a68-83ba-3ba439f590f0.png)
这是个简单的代码，是从示例里面抄出来的
![image](https://user-images.githubusercontent.com/14273571/154058873-db603f48-3127-4f26-b8e2-5b32f8d4df49.png)
我ts和react项目基础比较薄弱，查了两天issues和百度无从下手，求问各位大佬接下来要做什么啊

**Comment by xiayukun** [comment]
版本是：
![image](https://user-images.githubusercontent.com/14273571/154180658-2c314c8b-8096-4e38-acfc-211f29797b1f.png)

**Comment by noonnightstorm** [comment]
@Zt448143356 有空帮忙看看
