### ISSUE TITLE
代码中漏了group的判空，导致使用节点组的时候，频繁报错

### ISSUE THREAD

**Issue by huangbaihei** [alibaba/butterfly#784]
![image](https://user-images.githubusercontent.com/37474464/154386794-21446393-9ee8-4682-9cbe-74f0f68d89c7.png)
![image](https://user-images.githubusercontent.com/37474464/154386988-abd076ee-b903-40a7-87dc-268929e68b0a.png)

**Comment by noonnightstorm** [comment]
好的，感谢，我们修复下

**Comment by noonnightstorm** [comment]
butterfly-dag@4.1.28
