### ISSUE TITLE
当节点组中存在多个已连线的子节点，删除节点组的时候报错 版本4.1.29

### ISSUE THREAD

**Issue by ayixidelu** [alibaba/butterfly#787]
![image](https://user-images.githubusercontent.com/37927198/155053260-b5618b30-fc9c-4494-8751-f2d191d79923.png)
![image](https://user-images.githubusercontent.com/37927198/155053416-79872785-ca9e-4495-9a14-8ec3bc1485ce.png)

**Comment by noonnightstorm** [comment]
butterfly-dag@4.1.30
