### ISSUE TITLE
拖动在节点组上面新建节点，无法直接进组，需要在画布新建完再拖动进组才能进组成功，希望能同时新建节点并进组

### ISSUE THREAD

**Issue by huangbaihei** [alibaba/butterfly#802]
![image](https://user-images.githubusercontent.com/37474464/160320220-5123c198-de28-4a79-abb5-e106a4f54d79.png)

**Comment by noonnightstorm** [comment]
可以的呀，你调用addnode的时候数据上带一个group属性即可

**Comment by huangbaihei** [comment]
> 
但是如果画布上存在多个节点组，或者多个节点组嵌套，我无法预判用户需要拖入哪个节点组，所以无法提前预置group属性的值

**Comment by noonnightstorm** [comment]
这个没办法的，需要客户自己处理，底层也没办法处理这个逻辑。但我可以提供一个思路：就是你拖动释放的位置，然后遍历一次group的位置，看看在哪个group里面，找到最深层次的group即可

**Comment by huangbaihei** [comment]
> 这个思路可以！爆赞
