### ISSUE TITLE
4.2.x 的 TreeCanvas 布局不正确

### ISSUE THREAD

**Issue by billyct** [alibaba/butterfly#812]
## The current behavior

4.2.x 版本的 example 涉及到 TreeCanvas 的似乎都布局不正确。

比如`demo/indented-tree` 这个例子，本地运行看起来是这样的：

<img width="608" alt="image" src="https://user-images.githubusercontent.com/1612364/162762999-fb1b87a6-3718-435f-a8eb-ab71be4f6624.png">

## The expected behavior

<img width="572" alt="image" src="https://user-images.githubusercontent.com/1612364/162763208-1e47e7d7-14ea-45be-88c2-8348de8500fd.png">

## Your environment(such as: Butterfly version、Browser version、OS and so on)

`Butterfly version`:
4.2.x
`Browser version`:
Chrome Version 100.0.4896.75
`OS`:
macOS

## Steps To Reproduce, Maybe you can provide a simple demo.
 

[官方的 example](https://github.com/alibaba/butterfly/tree/master/example)

如果把 `butterfly-dag` 换成 `4.1.33` 就没有问题。

**Comment by noonnightstorm** [comment]
好的，收到，我去看看

**Comment by noonnightstorm** [comment]
butterfly-dag@4.2.5 已修复，感谢反馈
