### ISSUE TITLE
想实现这种折线的效果

### ISSUE THREAD

**Issue by XzyZachary** [alibaba/butterfly#817]
<img width="124" alt="企业微信20220427-163334@2x" src="https://user-images.githubusercontent.com/16535001/165476898-c2270fbe-f407-4ac2-bc55-2d98912065c6.png">
打扰大佬，我想实现这种折线的效果可以吗？

**Comment by noonnightstorm** [comment]
这种用曼哈顿折线就ok，小蝴蝶本身就支持了，但要设置endpoint中的orientation属性

**Comment by XzyZachary** [comment]
> 这种用曼哈顿折线就ok，小蝴蝶本身就支持了，但要设置endpoint中的orientation属性

好嘞，谢谢~ 我后来成功了，之前一直不行原来是endpoint的orientation设置的不正确导致的，如果设置不正常，会报错~
