### ISSUE TITLE
butterfly-vue库，可以打包一份未压缩的js文件吗

### ISSUE THREAD

**Issue by lwn-ysy** [alibaba/butterfly#819]
## What problem does this feature solve?

butterfly-vue，可以打包一份未压缩的js文件吗，方便微调
![图片](https://user-images.githubusercontent.com/45418726/167072669-f819bc80-4d71-4871-a21d-345c846b2340.png)

像butterfly-dag
![图片](https://user-images.githubusercontent.com/45418726/167072801-f3a3e451-cc98-4e13-992a-89b00333ee21.png)

**Comment by Zt448143356** [comment]
是可以的。不过要迟一些了。
给你个最快速的解决方案：
方案一： clone 源码，自己改一下打包混淆压缩的这部分，然后link到项目中调试
方案二：直接把混淆后的代码格式化，然后调试。

方案一最好，方案二可读性估计没有那么好。

**Comment by lwn-ysy** [comment]
好的，可以，谢谢了。
