### ISSUE TITLE
滚轮缩放感觉是反的

### ISSUE THREAD

**Issue by Dellear** [alibaba/butterfly#824]
## What problem does this feature solve?

希望开放滚轮缩放反转控制。
一般的向外滚动是放大，向内滚动是缩小。（echarts、高德地图等是这样表现的）
然而butterfly的表现是反着的。

请考虑下是否需要统一，请开放配置。
或者如果认为是个bug，请修复下吧

**Comment by noonnightstorm** [comment]
mac和window的用户的习惯不一样，同时我们也开放了配置的：https://github.com/alibaba/butterfly/blob/master/docs/zh-CN/canvas.md#canvassetzoomable-boolean-boolean
