### ISSUE TITLE
小蝴蝶仅点击节点后，画布undo抛错

### ISSUE THREAD

**Issue by Ethan9809** [alibaba/butterfly#827]
抛错如下：

![image](https://user-images.githubusercontent.com/33758524/171352537-fc975154-569e-47d3-907e-4e736c9e2b84.png)

排查原因：
_system:dragNodeEnd，触发，会放进actionQueue里，逻辑如下

![image](https://user-images.githubusercontent.com/33758524/171352818-d73af333-fea8-47ce-b79d-379327e65e1f.png)

如果actionQueue只有_system:dragNodeEnd动作时，这里指针会退两下，step就会变成空的，下面逻辑就会抛错

![image](https://user-images.githubusercontent.com/33758524/171352908-c72f1cd1-d88f-4659-94ab-e76125058262.png)

**Comment by noonnightstorm** [comment]
#829
