### ISSUE TITLE
多选模式，选择框到画布边缘时，画布不支持自动延展

### ISSUE THREAD

**Issue by Ethan9809** [alibaba/butterfly#830]
## Your environment(such as: Butterfly version、Browser version、OS and so on)

`Butterfly version`:

`Browser version`:

`OS`:

**Comment by noonnightstorm** [comment]
哈哈～等待你的pr

**Comment by Ethan9809** [comment]
https://github.com/alibaba/butterfly/commit/ae2138bdd5eb9a110111d23abe3d8abde2d0c697
