### ISSUE TITLE
请问有vue的demo嘛？新手不太会React o(╥﹏╥)o

### ISSUE THREAD

**Issue by ijustlikeyou** [alibaba/butterfly#862]

**Comment by noonnightstorm** [comment]
有啊 @Zt448143356 t

**Comment by Zt448143356** [comment]
https://github.com/alibaba/butterfly/tree/master/vue/example
有vue2的文档。
vue3的话，你需要使用原生butterfly-dag来开发，这个部分就没有demo了。这个部分其实就正常写js。

**Comment by ijustlikeyou** [comment]
哦哦，看到了，非常感谢！

**Comment by yeyuliang2015** [comment]
butterfly本身不强依赖前端具体框架吧？

**Comment by Zt448143356** [comment]
butterfly-dag是原生js的。不强依赖于任何前端框架。
