### ISSUE TITLE
最新版本4.3.6升级报错，定位到有大小写问题

### ISSUE THREAD

**Issue by l695290718** [alibaba/butterfly#864]
![image](https://user-images.githubusercontent.com/43233604/177463607-91d46af2-1f88-48a5-809f-303adaaf69cd.png)
![image](https://user-images.githubusercontent.com/43233604/177463647-380750bd-1654-41ed-9949-12de28b6deb8.png)
![image](https://user-images.githubusercontent.com/43233604/177463674-5d3224c0-5c78-4983-a198-0d9e11f7854b.png)

**Comment by noonnightstorm** [comment]
这块@AceLeeWinnie 统一修改过这个api的大小写的

**Comment by noonnightstorm** [comment]
这次是我们v4的api设计不合理，大小写有问题导致的，麻烦你修改下大小写了，很抱歉。下次假如有api改造我会让大家提交到下一个大版本，不影响当前版本。

**Comment by l695290718** [comment]
> 这次是我们v4的api设计不合理，大小写有问题导致的，麻烦你修改下大小写了，很抱歉。下次假如有api改造我会让大家提交到下一个大版本，不影响当前版本。

这个是你们源码里面的，需要你们修改一下，不然这个插件没法用了
![image](https://user-images.githubusercontent.com/43233604/177527714-9dbee34b-e65c-40cc-886f-45ce7ba573dd.png)

**Comment by l695290718** [comment]
@noonnightstorm
