### ISSUE TITLE
可以保存当前画布内容，方便下次读取以后直接使用上次保存的画布吗？

### ISSUE THREAD

**Issue by W-xf** [alibaba/butterfly#866]
## What problem does this feature solve?

可以保存当前画布内容，包括节点、边和数据等，下次读取上次保存的画布以后直接使用吗？可以让编辑，修改更加方便。

**Comment by noonnightstorm** [comment]
当然可以啊，你可以从后端获取回来，然后调用draw的方法就ok啦～

**Comment by W-xf** [comment]
> 当然可以啊，你可以从后端获取回来，然后调用draw的方法就ok啦～

非常感谢，有例子可以学习一下吗？
