### ISSUE TITLE
网格线未响应缩放和移动

### ISSUE THREAD

**Issue by Fnxxxxo** [alibaba/butterfly#872]
## The current behavior
当前设置了网格线后，网格线表现为一个全屏固定遮罩。既不随画布缩放，也不随画布移动。

## The expected behavior
除非元素移动，否则与所有元素的位置绑定，画布移动和缩放时，与元素同比例缩放和位移。

## Your environment(such as: Butterfly version、Browser version、OS and so on)

`Butterfly version`: 4.3.7

`Browser version`: chrome 102.0.5005.115

`OS`: win10

## Steps To Reproduce, Maybe you can provide a simple demo.
 
```
  const canvas = new Canvas({
    root,
    moveable: true,
    draggable: true,
    linkable: true,
    disLinkable: true,
    theme: {
      autoFixCanvas: {
        enable: true,
        autoMovePadding: [20, 20, 20, 20],
      },
      isMouseMoveStopPropagation: true,
    },
  });

  canvas.setZoomable(true, true);
  canvas.draw({
    nodes: [{
      id: '1',
      top: 100,
      left: 100,
    }, 
  }, () => {
    canvas.setGridMode(true, {
      isAdsorb: true,
      theme: {
        shapeType: 'line',
        gap: 8,
        adsorbGap: 8,
        lineColor: '#606060',
        lineWidth: 0.1,
      },
    });
  });
```

**Comment by noonnightstorm** [comment]
这个不是bug，当时设计就是既不随画布缩放，也不随画布移动的哈～

**Comment by Fnxxxxo** [comment]
> 这个不是bug，当时设计就是既不随画布缩放，也不随画布移动的哈～

那看能不能转需求吧。毕竟网格线实际相当于经纬线，需要和画布绑定才能有助于布局。和视窗绑定就没啥用了。同类型产品比如diagramjs，processon，x6等都是这么操作的。
