### ISSUE TITLE
DIV调整尺寸后画布中线错位

### ISSUE THREAD

**Issue by coderFirework** [alibaba/butterfly#905]
下图是正常状态
![image](https://user-images.githubusercontent.com/11747531/198059936-15c1534a-1c57-4e6a-8951-52a5a6721904.png)
调整画布的div（root）的宽度后
![image](https://user-images.githubusercontent.com/11747531/198060714-3f208c02-cfb2-44c1-ac1d-efa80b08bb96.png)

**Comment by noonnightstorm** [comment]
请看一下canvas.updateRootResize的api
