### ISSUE TITLE
butterfly vue是否支持节点的自动布局

### ISSUE THREAD

**Issue by Wenjuan66** [alibaba/butterfly#909]
## What problem does this feature solve?
现在vue提供的例子里面，Node节点都是指定两个值来指定位置后，初始化渲染的，是否能够指定root节点的值后自动布局？

**Comment by Zt448143356** [comment]
支持的。你可以看一下vue的demo。在vue目录下。

**Comment by Wenjuan66** [comment]
![image](https://user-images.githubusercontent.com/48712516/203306081-bebcd36f-e88f-465b-b6ee-a3f415a3b92b.png)
Treedemo的例子存在这个报错是什么原因？只能渲染出Root节点

**Comment by Zt448143356** [comment]
确实存在这个问题，在dag版本为4.3.8是ok的。4.3.13的时候存在问题。应该是dag更新导致的这个bug。我后续修复下这个问题

**Comment by Zt448143356** [comment]
更新下dag。已经修复完毕

**Comment by Wenjuan66** [comment]
butterfly-dag版本换成了4.3.8版本，结果还是如截图所示

**Comment by Zt448143356** [comment]
![image](https://user-images.githubusercontent.com/48010552/204493482-52531587-32cf-4d05-8488-84a37f2e8a2a.png)
我是ok的啊。
https://github.com/Zt448143356/butterfly
你试试我仓库的example。
主仓库还没同步代码

**Comment by Wenjuan66** [comment]
![image](https://user-images.githubusercontent.com/48712516/204543131-5a4cd380-dbb1-4719-a3d7-d0eeddf00aad.png)
我试了一下，点击添加节点的时候有这个报错，是不是存在版本冲突呀，我已经试着降低过了：
vue/example/package.json：
{
  "name": "example",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve --port 9003",
    "build": "vue-cli-service build"
  },
  "dependencies": {
    "butterfly-dag": "^4.3.8",
    "butterfly-vue": "^1.0.21",
    "core-js": "^3.6.5",
    "element-ui": "^2.15.0",
    "lodash": "^4.17.21",
    "vue": "^2.6.11",
    "vue-router": "^3.5.1",
    "vuetify": "^2.5.8"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "node-sass": "^4.14.1",
    "sass": "^1.26.5",
    "sass-loader": "^7.3.1",
    "vue-template-compiler": "^2.6.11"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}

**Comment by Zt448143356** [comment]
我觉得是你版本的问题。先check下版本。

example的目录下的node_modules的vue版本是
![image](https://user-images.githubusercontent.com/48010552/204557570-b7e4849e-bbe6-492f-a2f0-5dfd746526be.png)

vue目录下的node_modules的dag的版本是
![image](https://user-images.githubusercontent.com/48010552/204557688-5d7fe805-9b62-467a-808e-d90bfa42088e.png)

dag: 4.3.16，vue:1.0.22

我的example预览效果：
![Kapture 2022-11-29 at 22 33 00](https://user-images.githubusercontent.com/48010552/204557908-11b89ebb-a11d-484f-8acc-ce2fc0765bb1.gif)

如果还是有问题。你可以试试其他框架，g6，x6等。

**Comment by Wenjuan66** [comment]
试了还是不行，就是版本的问题了，谢谢啦！

**Comment by Zt448143356** [comment]
意思是版本对了之后就可以了是吗？
如果搞定了麻烦关闭一下这个issue

**Comment by Wenjuan66** [comment]
我这还没调通，去尝试使用X6了
但看这个报错应该是版本的问题，那我先关啦
