### ISSUE TITLE
vue版本butterfly-dag4.3.13版本，改变数据中节点的left和top，画布节点位置不更新

### ISSUE THREAD

**Issue by leeJie1994** [alibaba/butterfly#910]
vue版本，数据中更改节点的left和top，画布中节点位置不更新（redrew重绘才会更新位置），尝试改变位置数据后，数据中插入新节点，画布中有新节点显示，但是旧节点的位置依旧未更新。butterfly-dag4.1.20版本是正常的，更新到4.3.13版本才出现这个问题。
![image](https://user-images.githubusercontent.com/30051774/202703440-e552ed27-6919-46a6-987a-8b44fec7c1c9.png)
![image](https://user-images.githubusercontent.com/30051774/202703555-48ba7758-3170-45f2-914d-1c771ea4284b.png)
![GIF](https://user-images.githubusercontent.com/30051774/202703697-3ced2560-86fd-4535-ad5e-bfad40ec5ad5.gif)

**Comment by Zt448143356** [comment]
我们尽快查一下问题。结果给你反馈。

**Comment by Zt448143356** [comment]
你确定这个butterfly-dag4.1.20版本是ok的吗？
我看了下代码这部分逻辑是欠缺的。我加下。修复后和你说。

**Comment by leeJie1994** [comment]
> 你确定这个butterfly-dag4.1.20版本是ok的吗？ 我看了下代码这部分逻辑是欠缺的。我加下。修复后和你说。

嗯嗯，好的。
对的，我这边用新旧版本进行了测试，4.1和4.2的版本都正常，节点数据的left和top值发生改变，画布节点位置就会更新。4.3版本，画布位置不会更新。

**Comment by Zt448143356** [comment]
修复完毕了你更新下依赖试一下，dag（4.3.16）和vue（1.0.21）都更新下。修复了不同的bug

**Comment by leeJie1994** [comment]
> 

![image](https://user-images.githubusercontent.com/30051774/203780216-61b332ea-78c3-41bd-a64c-0007aab81f0e.png)
更新之后，left和top赋值，画布依然未更新

**Comment by Zt448143356** [comment]
![Kapture 2022-11-24 at 20 47 07](https://user-images.githubusercontent.com/48010552/203788315-fb26650c-d721-4212-b88e-8b13ecdcdcef.gif)

![image](https://user-images.githubusercontent.com/48010552/203787036-6f987955-b86d-4d40-b7a8-eb289248b98c.png)

我是ok的，你可以看下vue的example。
或者这又是一个新的bug？

**Comment by leeJie1994** [comment]
> ![Kapture 2022-11-24 at 20 47 07](https://user-images.githubusercontent.com/48010552/203788315-fb26650c-d721-4212-b88e-8b13ecdcdcef.gif) [ ![Kapture 2022-11-24 at 20 47 07](https://user-images.githubusercontent.com/48010552/203788315-fb26650c-d721-4212-b88e-8b13ecdcdcef.gif) ](https://user-images.githubusercontent.com/48010552/203788315-fb26650c-d721-4212-b88e-8b13ecdcdcef.gif) [ ](https://user-images.githubusercontent.com/48010552/203788315-fb26650c-d721-4212-b88e-8b13ecdcdcef.gif)
> 
> ![image](https://user-images.githubusercontent.com/48010552/203787036-6f987955-b86d-4d40-b7a8-eb289248b98c.png)
> 
> 我是ok的，你可以看下vue的example。 或者这又是一个新的bug？



又再次进行了测试，使用splice替换数据，依然是画布位置依然无法更新，如下图
![GIF](https://user-images.githubusercontent.com/30051774/203962234-cde87399-6981-4988-9e2a-b32ac23e18b1.gif)
![1](https://user-images.githubusercontent.com/30051774/203962292-f49a9c23-fd25-4a3f-bad7-db6e70fa3f10.jpg)



设置1毫秒的时间差，先删除这个节点，再次添加这个节点，画布位置更新。但是会出现新的问题，已有的连接到该节点的连线，在画布中会断开，如下图
![GIF2](https://user-images.githubusercontent.com/30051774/203962963-bf075c94-8239-4068-ae87-fd4d8affaacf.gif)
![2](https://user-images.githubusercontent.com/30051774/203962995-5dcfbdde-35ab-449f-abdf-37b2beec1a23.jpg)


下载gitgub里最新的master代码，测试了里面vue中的example的demo，结果和上面是一样的，画布位置无更新，如下图
![GIF3](https://user-images.githubusercontent.com/30051774/203963404-867c25ee-d045-4bcf-9883-04784be90a5e.gif)
![3](https://user-images.githubusercontent.com/30051774/203963484-eb40c44a-3253-4668-85a6-e931da9f12e2.jpg)

**Comment by Zt448143356** [comment]
https://github.com/Zt448143356/butterfly
你试试我这个仓库的example。
我还没推送到官方库。
如果还不可以的话，请提供一个最小的复现demo。
example中是直接使用源码的。你可以在package中加一个vue版本。然后改一下引用方式。去使用npm上的包（来排除我发布npm版本代码不对的情况）

我自己都是测过的没有问题。你试试。

**Comment by Zt448143356** [comment]
layout和left和top不同共用的。这俩都是定位用的。
left和top是定位全部交给用户。
layout是直接根据布局算法来计算位置(自动布局)

**Comment by leeJie1994** [comment]
> layout和left和top不能同时使用的。这俩都是定位用的。 left和top是定位全部交给用户。 layout是直接根据布局算法来计算位置(自动布局)

好的
