### ISSUE TITLE
butterfly-vue的树状图节点收缩该怎么使用

### ISSUE THREAD

**Issue by alonetu** [alibaba/butterfly#916]
// 当canvas为TreeCanvas时Node可选TreeNode;

我使用树状布局的时候，在自定义的节点组件里面打印节点信息，发现节点还是Node类型，不是TreeNode，这样就不能调用节点的展开和收起方法，请问一下butterfly-vue的自定义节点该如何使用展开和收起呢？有没有大佬解答一下，感谢

**Comment by noonnightstorm** [comment]
@Zt448143356

**Comment by Zt448143356** [comment]
> // 当canvas为TreeCanvas时Node可选TreeNode;
> 
> 我使用树状布局的时候，在自定义的节点组件里面打印节点信息，发现节点还是Node类型，不是TreeNode，这样就不能调用节点的展开和收起方法，请问一下butterfly-vue的自定义节点该如何使用展开和收起呢？有没有大佬解答一下，感谢

节点是node不是treeNode这里确实是一个bug（我后续修复下）。但是这个部分应该是不影响你去使用的。这里建议脱离butterfly的TreeNode的方法。

你可以自己实现的。
butterfly中的展开收起，其实是数据没变，就把这个节点的child都给销毁了。

在vue中是数据驱动的，你自己处理数据就好了。
有多种处理方式
1. 你通过数据控制收齐展开，收起就把这部分数据给去掉，展开就加上。（性能差一些）：点击的时候处理数据
2. 你通过数据控制每个节点的参数，然后通过参数来控制节点的显影（display，这个性能好一些）：点击的时候处理数据
3. ....应该还有很多方法。

vue中把所有的数据都交给你了。你可以做任何处理。节点的渲染也是收到你控制的。（数据驱动是vue、react等的框架的重点）

**Comment by alonetu** [comment]
多谢，这个问题确实可以通过map结构来做处理，自己管理数据来进行渲染达到收缩的效果。再次感谢
