### ISSUE TITLE
Dragging node in nested group not working

### ISSUE THREAD

**Issue by JensWinkler91** [alibaba/butterfly#919]
## The current behavior
I have one node and two groups: _Group1_ and _Group2_. _Group 2_ is included in _Group 1_. I can drag the node into _Group 2_ . and move _Group 2_ into _Group 1_. However, after dragging the node into _Group 1_ i can't drag the node back to _Group 2_ without removing _Group 2_ from _Group 1_ first.

**Dragging node into Group 2 and than into Group 1:**
![butterfly-a-javascript-based-data-driven-nodal-choreography-component-library_QOHsB9g3](https://user-images.githubusercontent.com/81766522/210458197-7aab371b-e78f-44b4-bd0c-78e05110a43c.gif)

**Can't drag node into Group 2:**
![butterfly-a-javascript-based-data-driven-nodal-choreography-component-library_HPpZQOGZ](https://user-images.githubusercontent.com/81766522/210458576-492ee122-61bc-462f-80c9-3e420c50feef.gif)

## The expected behavior
After dragging a node from a parent group into a nested/included group, the node should be member of the nested Group.

## Your environment(such as: Butterfly version、Browser version、OS and so on)

`Butterfly version`:
"butterfly-dag": "4.3.16"
"butterfly-react": "1.0.1"

`Browser version`: 
Google Chrome (Version 108.0.5359.125)

`OS`:
Windows 10

## Steps To Reproduce:
You can reproduce the behavior using your demo [Schedule](https://butterfly-dag.gitee.io/butterfly-dag/demo/schedule) and the following data:

```
import` Node from './node';
import Edge from './edge';

export default {
  nodes: [
   {
      id: '15',
      label: 'Node',
      className: 'icon-background-color',
      iconType: 'icon-guanlian',
      top: 205,
      left: 300,
      Class: Node,
      endpoints: [{
        id: 'top',
        orientation: [0, -1],
        pos: [0.5, 0]
      }]
    },
  ],
  edges: [],
  groups: [{
    id: 'Group1',
    options: {
      title: 'Group 1'
    },
    top: 310,
    left: 185,
    width: 500,
    height: 300,
    resize: true
  },
  {
    id: 'Group2',
    options: {
      title: 'Group 2'
    },
    top: 0,
    left: 0,
    width: 300,
    height: 200,
    resize: true
  }],
};
```

Note that in index.jsx includeGroup is set to true.

```
import React, {Component} from 'react';
import ReactDOM from 'react-dom';
import {Canvas} from 'butterfly-dag';
import mockData from './data.js';
import 'butterfly-dag/dist/index.css';
import './iconfont.css';
import './index.less';

class Scene4New extends Component {
  constructor() {
    super();
  }
  componentDidMount() {
    let root = document.getElementById('dag-canvas');
    this.canvas = new Canvas({
      root: root,
      disLinkable: true, // 可删除连线
      linkable: true,    // 可连线
      draggable: true,   // 可拖动
      zoomable: true,    // 可放大
      moveable: true,    // 可平移
      theme: {
        edge: {
          shapeType: 'AdvancedBezier',
        },
        group: {
            includeGroups: true
        }
     }
    });
    this.canvas.draw(mockData);
    this.canvas.on('events', (data) => {
      // console.log(data);
    });
  }
  render() {
    return (
      <div className='schedule'>
        <div className="schedule-canvas" id="dag-canvas">
        </div>
      </div>
    );
  }
}

ReactDOM.render(<Scene4New />, document.getElementById('root'));
```

**Comment by noonnightstorm** [comment]
ok, I got it. I will fix it as soon as possible~

**Comment by JensWinkler91** [comment]
Thank you! Please let me know once it's fixed.

**Comment by noonnightstorm** [comment]
butterfly-dag@4.3.17 has fixed it.

**Comment by JensWinkler91** [comment]
Thanks for the quick bug fix!
