### ISSUE TITLE
Wrong node position after dragging a node from parent group into a nested group

### ISSUE THREAD

**Issue by JensWinkler91** [alibaba/butterfly#921]
## The current behavior
Dragging a node from a parent group into a nested group leads into a wrong node position.

![nervous-pateu-jqjl52-codesandbox-google-chrome-2023-01-05-14-52-43-trim_jqffXxBS](https://user-images.githubusercontent.com/81766522/210799584-ea05fcd1-add5-4d53-8bd0-f5ed0438fad9.gif)

## The expected behavior
The node should be rendered inside the nested group after dragging it from the parent group into the nested group.

## Your environment(such as: Butterfly version、Browser version、OS and so on)

`Butterfly version`:
"butterfly-dag": "4.3.17"
"butterfly-react": "1.0.1"

`Browser version`:
Google Chrome (Version 108.0.5359.125)

`OS`:
Windows 10

## Steps To Reproduce:
The bug can be reprocuded with this [codesandbox example](https://codesandbox.io/s/butterfly-wrong-node-position-jqjl52). Just drag the node from the parent group into the nested group.

**Comment by noonnightstorm** [comment]
ok， got it

**Comment by JensWinkler91** [comment]
Great. Please let me know once it' fixed.

**Comment by JensWinkler91** [comment]
Sorry, for the late reply. I tested it recently. It works like a charm. Thx for that bug fix!
