### ISSUE TITLE
butterfly-vue 如何支持「链接」、「断开」等操作的 interceptor ？

### ISSUE THREAD

**Issue by Nelk98** [alibaba/butterfly#925]

**Comment by noonnightstorm** [comment]
@Zt448143356

**Comment by Zt448143356** [comment]
butterfly-vue的底层butterfly没有这个功能。
但是你可以这样去实现。
当线断开的时候，你去判断是否是可以断开的线，不可断开的话，你在给它连回去就好了。
这里需要注意的就是连回去会触发一些事件，这里需要规避一下。
