### ISSUE TITLE
node节点添加自定义锚点dom，出现初始化卡顿。

### ISSUE THREAD

**Issue by yijiu986** [alibaba/butterfly#946]
## node节点添加自定义锚点dom，出现初始化卡顿。

运行环境：butterfly-dag+vue  。

场景初始化时，有200多个节点，节点有100多个节点是需要每个节点大约20个锚点。 自定义锚点是节点的mounted后通过addpoint 添加的整个渲染卡顿时间在10秒钟，内存分析发现，baseEndpoint.js文件中_init（）方法的
```
  // 计算width,height,left,top
      this._width = $(this.dom).outerWidth();
      this._height = $(this.dom).outerHeight();
      
      this._left = this._coordinateService._terminal2canvas('x', $(this.dom).offset().left + this._coordinateService.scrollLeft);
      this._top = this._coordinateService._terminal2canvas('y', $(this.dom).offset().top + this._coordinateService.scrollTop);

      this._posTop = this._top;
      this._posLeft = this._left;
```
重复字数较多，影响了大约3秒钟。自定义的锚点布局都是确定的，为什么还会局计算这个排版位置？
![image](https://github.com/alibaba/butterfly/assets/7589175/2d7a8f3c-1744-4dd8-b790-3be80a52a634)

![image](https://github.com/alibaba/butterfly/assets/7589175/da9c5ff4-6b98-43b5-aca4-61445074573c)

**Comment by noonnightstorm** [comment]
能提供下最小demo给我优化下么？

**Comment by noonnightstorm** [comment]
![IMG_3779](https://github.com/alibaba/butterfly/assets/1336049/daed1c38-77df-43c6-b8bb-3e85dc42ca03)
可以加钉钉服务群

**Comment by noonnightstorm** [comment]
是的，vue做数据绑定，肯定会慢一些，原生肯定会更快

**Comment by noonnightstorm** [comment]
> [案例.zip](https://github.com/alibaba/butterfly/files/11664232/default.zip) ![image](https://user-images.githubusercontent.com/7589175/243686379-2a847786-9450-410b-a87a-2034d6aecbb5.png)
> 
> 实际使用的是vue的，这个案例里还稍微快点，vue版本好像后面还会重新绘制。

我尝试了一下各个demo，我感觉挺快的呀

**Comment by noonnightstorm** [comment]
我看了较久，原生版已经没办法再压缩性能了，现在已经基本调得最优。现在demo的界面上200个节点+2000个锚点+361条线段，能在3s+内渲染已经是比较理想的了

**Comment by noonnightstorm** [comment]
我看了好一会，原生版已经没办法再压缩性能了，现在已经基本调得最优。现在demo的界面上200个节点+2000个锚点+361条线段，能在3s+内渲染已经是比较理想的了
![image](https://github.com/alibaba/butterfly/assets/1336049/d17475e3-0d6c-4119-b427-617e4732aed3)

**Comment by yijiu986** [comment]
锚点是固定的，在后期添加锚点的时候是否可以考虑不进行位置获取设置。
![image](https://github.com/alibaba/butterfly/assets/7589175/6bdcf122-bee7-4e8f-b928-b5b9bddc52ab)

**Comment by noonnightstorm** [comment]
> 锚点是固定的，在后期添加锚点的时候是否可以考虑不进行位置获取设置。 ![image](https://user-images.githubusercontent.com/7589175/245421394-6bdcf122-bee7-4e8f-b928-b5b9bddc52ab.png)


你这个情况太特殊了，我建议你继承我的endpoint的类，然后进行重写_init的方法

**Comment by yijiu986** [comment]
好的
