### ISSUE TITLE
TreeCanvas类型，layout为compactBox。我如果不调用draw，手动去调用autoLayout方法的话，有疑问

### ISSUE THREAD

**Issue by Jevin0** [alibaba/butterfly#951]
![image](https://github.com/alibaba/butterfly/assets/69580637/c00d2e63-6b18-446a-964e-1c9f3d159ae0)
如果我是手动调用autoLayout的话，我看源码中。这里只会拿到最开头的一个属性为isRoot值为true的节点，后面的节点都不会布局？这里是还没完善吗？

**Comment by noonnightstorm** [comment]
这里是没问题的，isRoot的节点中，里面有children的，里面就是一颗树的结构
