### ISSUE TITLE
Uncaught ReferenceError: _drawPath is not defined

### ISSUE THREAD

**Issue by vaskus** [alibaba/butterfly#952]
## The current behavior
Canvas create
```
Create canvas:
new Canvas({
      root: elementRef,
      moveable: true,
      draggable: false,
      linkable: true,
      theme: {
        group: { type: 'normal' },
        edge: {
          type: 'endpoint',
          shapeType: 'Manhattan',
          hasRadius: true,
          isExpandWidth: true,
          draggable: true,
          arrow: false,
        },
        endpoint: { position: [], limitNum: 10, linkableHighlight: true },
      },
    });

Adding Edge for canvas:
this.edgeIdIncrement += 1;
    const edge = this.canvas.addEdge({
      id: this.edgeIdIncrement,
      source,
      target,
      sourceNode,
      targetNode,
      type: 'endpoint',
    });
```

When trying to draw edge: Error happens:
```
Uncaught ReferenceError: _drawPath is not defined
    at Object.drawManhattan (index.js:26740:13)
    at BaseEdge._calcPath (index.js:20104:28)
    at BaseEdge.redraw (index.js:20250:27)
    at BaseEdge._updatePath (index.js:20447:12)
    at HTMLDivElement.mouseMoveEvent (index.js:15829:39)
    at _ZoneDelegate.invokeTask (zone.js:409:31)
    at Zone.runTask (zone.js:178:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:490:34)
    at invokeTask (zone.js:1664:18)
    at globalCallback (zone.js:1695:29)
```

## The expected behavior
Edge Should be dragged on needed position.

## Your environment
`Butterfly version`: `4.3.24`

`Browser version`: `Version 114.0.5735.90 (Official Build) (64-bit)` 

`Angular version`: `15.2.5`

**Comment by noonnightstorm** [comment]
`this.canvas.addEdge` please add Class attr

**Comment by noonnightstorm** [comment]
butterfly-dag@4.3.25 has fix it

**Comment by noonnightstorm** [comment]
ok，I try to fix

**Comment by limy135302065** [comment]
I encountered the same problem.Has the problem been resolved
@noonnightstorm Thanks

**Comment by noonnightstorm** [comment]
> I have kind of problem with Manhattan edges, when I add new edge, some old edges can't drag
> 
> index.js:20430 Uncaught TypeError: Cannot read properties of undefined (reading 'index') at CustomEdge._updatePath (index.js:20430:1) at HTMLDivElement.mouseMoveEvent (index.js:15829:1) _updatePath @ index.js:20430 mouseMoveEvent @ index.js:15829

Can you provide a demo ？ I have tied many times, but i didn't meet.

**Comment by noonnightstorm** [comment]
> I have kind of problem with Manhattan edges, when I add new edge, some old edges can't drag
> 
> index.js:20430 Uncaught TypeError: Cannot read properties of undefined (reading 'index') at CustomEdge._updatePath (index.js:20430:1) at HTMLDivElement.mouseMoveEvent (index.js:15829:1) _updatePath @ index.js:20430 mouseMoveEvent @ index.js:15829

Can you provide a demo ？ I have tied many times, but i didn't meet.

**Comment by noonnightstorm** [comment]
> I encountered the same problem.
> 
> Uncaught TypeError: Cannot read properties of undefined (reading 'index') at BaseEdge._updatePath (index.js:20429:1) at HTMLDivElement.mouseMoveEvent (index.js:15829:1)
> 
> @noonnightstorm Thanks

Can you provide a demo ？ I have tied many times, but i didn't meet.

**Comment by rcole1919** [comment]
@noonnightstorm 

https://github.com/alibaba/butterfly/assets/59145709/aeb9756c-ab17-4b75-87f4-441eb00f67b3

**Comment by noonnightstorm** [comment]
> @noonnightstorm , I've just add a draggable flag
> 
>  butterfly-bug_pYo3N1QT.mp4

butterfly-dag@4.3.27 has fixed it
