### ISSUE TITLE
canvas.draw / canvas.redraw always triggers event 'system.link.connect'

### ISSUE THREAD

**Issue by JensWinkler91** [alibaba/butterfly#958]
## The current behavior
Calling `canvas.draw()` always triggers the `'system.link.event'`

## The expected behavior
I would exepect that this event isn't triggered while calling `draw ` or `redraw`. 
At least there should be a possibility to differentiate between a user input (user connects two nodes) and the draw functions. 

_Reason:_
I'd like to use this event to create a relationship in my backend. 
Triggering the `'system.link.event'` after `draw / redraw` leads into wrong data.

Butterfly version:
"butterfly-dag": "4.3.27"

Browser version:
Google Chrome (Version 108.0.5359.125)

OS:
Windows 10

**Comment by noonnightstorm** [comment]
By Design. You can listen 'system.link.event' after draw callback

**Comment by JensWinkler91** [comment]
Thanks, it works!
