### ISSUE TITLE
Redraw node / group

### ISSUE THREAD

**Issue by JensWinkler91** [alibaba/butterfly#962]
## What problem does this feature solve?

I'm missing a function to redraw a single node or group.

**I tried:**

1. Removing and adding a node. The problem is that the edges of the node disappear.
2. Using `canvas.redraw` (.e.g. `this.canvas.redraw({nodes: [noteToRedraw]})`) let all nodes/groups/edges disappear.
3. `canvas.draw` doesn't redraw the node.

So is there any possiblity to redraw a single node/group?

**Comment by noonnightstorm** [comment]
You can`t redraw a single node or group by canvas.draw or canvas.redraw . You should extend my BaseNode Class and  rewrite a funciotn to change dom to update node by yourself.

**Comment by noonnightstorm** [comment]
canvas.redraw will remove all nodes and add nodes again.

**Comment by JensWinkler91** [comment]
Thanks for your advice. I did as you mentioned and it works now.

Anyway i think it'd be helpfull if there is a `redraw`-function that calls the `BaseNode.draw(obj)` function and replaces the old element with the new element.

**Comment by noonnightstorm** [comment]
It might be more convenient, but the performance will be very bad.

**Comment by JensWinkler91** [comment]
Alright, thanks for your help!
