### ISSUE TITLE
Invert zooming by wheel scrolling

### ISSUE THREAD

**Issue by rcole1919** [alibaba/butterfly#964]
Is there option to invert zoom effect by the mouse wheel scrolling?

**Default behaviour:**
Scroll up and scale decreases,
Scroll down and scale increases.

**Desired behavior:**
Scroll up and scale increases,
Scroll down and scale decreases.

For example, Figma has same effect.

**Comment by JensWinkler91** [comment]
I guess you're looking for `canvas.setZoomable(true, true)`.
If the second parameter is true, the zoom direction is inverted.

**Comment by rcole1919** [comment]
Are there any options to get it through the canvas config?
I know, you don't support React-Buttrerfly anymore. But It seems the config option may be a possible solution

**Comment by JensWinkler91** [comment]
As I'm not a contributor so i can't answer that question.
As a workaround you could access the canvas using a reference, .e.g.
 `ref={r => this.canvasRef.current = r}`.

That's how i handled it before i stopped using butterfly-react and used butterfly-dag instead.

**Comment by rcole1919** [comment]
It seems, this workaround helps
```
useEffect(() => {
	ref.current.canvas.setZoomable(true, true);
}, []);
```
